import Link from "next/link";
import { AlertTriangle, Archive, CalendarDays, ClipboardCheck, FileText, Gauge, Pencil, ShieldCheck, Truck, Wrench } from "lucide-react";
import { AssignmentForm, EquipmentDocumentForm, EquipmentStatusForm, MaintenanceScheduleForm, ReadingForm } from "../EquipmentForms";
import { archiveEquipment, completeEquipmentMaintenance, resolveEquipmentProblem, returnEquipmentAssignment } from "../actions";
import { PlatformFrame } from "@/components/PlatformFrame";
import { SetupRequired } from "@/components/SetupRequired";
import { getAuthenticatedPlatformContext } from "@/lib/auth/pageContext";
import { hasAllowedRole, platformRoleGroups } from "@/lib/auth/roles";
import { getEquipmentAsset, getEquipmentFormOptions } from "@/lib/data/equipment";

type Props = { params: Promise<{ assetId: string }>; searchParams: Promise<{ created?: string; updated?: string }> };

export default async function EquipmentDetailPage({ params, searchParams }: Props) {
  const { assetId } = await params;
  const query = await searchParams;
  const context = await getAuthenticatedPlatformContext(`/admin/equipment/${assetId}`);
  if (!context.configured) return <SetupRequired title="Configure Supabase before opening equipment" />;
  const [detailResult, options] = await Promise.all([getEquipmentAsset(assetId), getEquipmentFormOptions()]);
  const asset = detailResult.data;
  const canOverride = hasAllowedRole(context.roles, platformRoleGroups.accessApproval);

  return <PlatformFrame active="equipment" roles={context.roles} userEmail={context.user.email}><div className="shell app-content equipment-detail-page">
    <Link className="crew-back-link" href="/admin/equipment">Back to equipment</Link>
    {detailResult.error ? <DataWarning message={detailResult.error} /> : null}{options.error ? <DataWarning message={options.error} /> : null}
    {query.created ? <p className="form-message success">Equipment added.</p> : null}{query.updated ? <p className="form-message success">Equipment changes saved.</p> : null}
    {!asset ? <section className="empty-state"><h2>Equipment not found</h2><p>This record is unavailable to the current account.</p></section> : <>
      <section className="page-heading commerce-heading"><div><p className="surface-label"><Truck size={17} />{asset.asset_number}</p><h1>{asset.name}</h1><p>{[asset.manufacturer, asset.model, asset.model_year].filter(Boolean).join(" ") || title(asset.category)}</p></div><div className="action-row"><span className={`equipment-status status-${asset.status}`}>{title(asset.status)}</span><Link className="primary-action" href={`/admin/equipment/${asset.id}/edit`}><Pencil size={18} />Edit</Link></div></section>
      {asset.status === "out_of_service" ? <section className="equipment-safety-banner"><ShieldCheck size={24} /><div><strong>Out of service</strong><p>Do not assign or use this equipment until unsafe problems are resolved and staff deliberately returns it to service.</p></div></section> : null}
      <section className="equipment-metric-grid"><Metric label="Mileage" value={asset.current_mileage == null ? "Not recorded" : `${asset.current_mileage.toLocaleString()} mi`} /><Metric label="Engine hours" value={asset.current_hours == null ? "Not recorded" : `${asset.current_hours.toLocaleString()} hr`} /><Metric label="Location" value={asset.location_label || "Not set"} /><Metric label="Next inspection" value={asset.next_inspection_due_at ? formatDate(asset.next_inspection_due_at) : "Not scheduled"} /></section>
      <section className="detail-grid">
        <article className="detail-panel"><PanelTitle icon={<ClipboardCheck size={18} />} title="Identity" /><dl className="crew-detail-list"><Row label="Category" value={title(asset.category)} /><Row label="Serial" value={asset.serial_number || "Not set"} /><Row label="VIN" value={asset.vin || "Not set"} /><Row label="Plate" value={asset.license_plate || "Not set"} /><Row label="Ownership" value={asset.ownership_type ? title(asset.ownership_type) : "Not set"} /></dl></article>
        <article className="detail-panel"><PanelTitle icon={<ShieldCheck size={18} />} title="Safety" /><dl className="crew-detail-list"><Row label="Class" value={asset.safety_class || "Not set"} /><Row label="Required PPE" value={asset.ppe_required || "Not set"} /><Row label="Checklist" value={asset.inspection_template_key ? title(asset.inspection_template_key) : "No fixed checklist"} /></dl></article>
        <article className="detail-panel wide-detail-panel"><PanelTitle icon={<Truck size={18} />} title="Assignments" />{asset.equipment_assignments?.length ? <div className="linked-record-list">{asset.equipment_assignments.slice().sort(byNewest("starts_at")).map((assignment) => <article className="linked-record" key={assignment.id}><strong>{assignment.profiles?.full_name || assignment.profiles?.email || assignment.jobs?.service_type?.replaceAll("_", " ") || assignment.schedule_events?.title || "Equipment assignment"}</strong><span>{formatDateTime(assignment.starts_at)}{assignment.ends_at ? ` to ${formatDateTime(assignment.ends_at)}` : " onward"}{assignment.returned_at ? " · Returned" : ""}</span>{assignment.created_by_profile ? <small>Assigned by {assignment.created_by_profile.full_name || assignment.created_by_profile.email || "staff"}</small> : null}{assignment.conflict_override_reason ? <small className="attention-text">Override: {assignment.conflict_override_reason}</small> : null}{!assignment.returned_at ? <form action={returnEquipmentAssignment}><input name="asset_id" type="hidden" value={asset.id} /><input name="assignment_id" type="hidden" value={assignment.id} /><button className="secondary-action" type="submit">Mark returned</button></form> : null}</article>)}</div> : <p className="inline-empty">No assignments yet.</p>}</article>
        <article className="detail-panel"><PanelTitle icon={<Wrench size={18} />} title="Maintenance" />{asset.equipment_maintenance_schedules?.length ? asset.equipment_maintenance_schedules.map((schedule) => <article className="linked-record equipment-maintenance-row" key={schedule.id}><strong>{schedule.title}</strong><span>{dueLabel(schedule, asset.current_mileage, asset.current_hours)}</span>{schedule.instructions ? <small>{schedule.instructions}</small> : null}<details><summary>Record completed service</summary><form action={completeEquipmentMaintenance} className="crm-form"><input name="asset_id" type="hidden" value={asset.id} /><input name="schedule_id" type="hidden" value={schedule.id} /><div className="form-grid-two"><label>Mileage<input name="mileage_at_service" step="0.1" type="number" /></label><label>Hours<input name="hours_at_service" step="0.1" type="number" /></label></div><label>Completion notes<textarea name="completion_notes" rows={2} /></label><button type="submit">Complete maintenance</button></form></details></article>) : <p className="inline-empty">No recurring maintenance schedules yet.</p>}<h3 className="equipment-history-heading">Service history</h3>{asset.equipment_maintenance_records?.filter((record) => record.status === "completed").length ? asset.equipment_maintenance_records.filter((record) => record.status === "completed").sort((left, right) => new Date(right.completed_at ?? right.created_at).getTime() - new Date(left.completed_at ?? left.created_at).getTime()).slice(0, 8).map((record) => <article className="linked-record" key={record.id}><strong>{record.title}</strong><span>{record.completed_at ? formatDateTime(record.completed_at) : "Completed"}{record.mileage_at_service != null ? ` · ${record.mileage_at_service.toLocaleString()} mi` : ""}{record.hours_at_service != null ? ` · ${record.hours_at_service.toLocaleString()} hr` : ""}</span>{record.description ? <small>{record.description}</small> : null}</article>) : <p className="inline-empty">No completed service recorded yet.</p>}</article>
        <article className="detail-panel"><PanelTitle icon={<AlertTriangle size={18} />} title="Open problems" />{asset.equipment_problem_reports?.filter((report) => !["resolved", "dismissed"].includes(report.status)).length ? asset.equipment_problem_reports.filter((report) => !["resolved", "dismissed"].includes(report.status)).map((report) => <article className={`linked-record equipment-problem ${report.severity}`} key={report.id}><strong>{report.title}</strong><span>{title(report.severity)} · {title(report.status)} · {formatDateTime(report.created_at)}</span><p>{report.description}</p>{report.photo_signed_url ? <a className="secondary-action" href={report.photo_signed_url} rel="noreferrer" target="_blank">Open private photo</a> : null}<details><summary>Resolve problem</summary><form action={resolveEquipmentProblem} className="crm-form"><input name="asset_id" type="hidden" value={asset.id} /><input name="report_id" type="hidden" value={report.id} /><label>Resolution notes<textarea name="resolution_notes" required rows={2} /></label><button type="submit">Mark resolved</button></form></details></article>) : <p className="inline-empty">No open equipment problems.</p>}</article>
        <article className="detail-panel wide-detail-panel"><PanelTitle icon={<ClipboardCheck size={18} />} title="Inspection history" />{asset.equipment_inspections?.length ? <div className="linked-record-list">{asset.equipment_inspections.slice().sort(byNewest("inspected_at")).map((inspection) => <article className="linked-record" key={inspection.id}><strong>{title(inspection.template_key)} · {title(inspection.overall_result)}</strong><span>{formatDateTime(inspection.inspected_at)} by {inspection.profiles?.full_name || inspection.profiles?.email || "staff"}</span>{inspection.notes ? <p>{inspection.notes}</p> : null}</article>)}</div> : <p className="inline-empty">No inspections submitted yet.</p>}</article>
        <article className="detail-panel"><PanelTitle icon={<Gauge size={18} />} title="Reading history" />{asset.equipment_readings?.length ? asset.equipment_readings.slice().sort(byNewest("recorded_at")).slice(0, 12).map((reading) => <article className="linked-record" key={reading.id}><strong>{reading.reading_value.toLocaleString()} {reading.reading_type === "mileage" ? "mi" : "hr"}</strong><span>{formatDateTime(reading.recorded_at)} · {title(reading.source)}</span>{reading.correction_reason ? <small>Correction: {reading.correction_reason}</small> : null}</article>) : <p className="inline-empty">No readings recorded yet.</p>}</article>
        <article className="detail-panel"><PanelTitle icon={<FileText size={18} />} title="Private documents" />{asset.equipment_documents?.length ? asset.equipment_documents.map((document) => <article className="linked-record" key={document.id}><strong>{document.title}</strong><span>{title(document.document_type)}{document.expires_at ? ` · expires ${formatDate(document.expires_at)}` : ""}</span>{document.signed_url ? <a className="secondary-action" href={document.signed_url} rel="noreferrer" target="_blank">Open private file</a> : null}</article>) : <p className="inline-empty">No registration, insurance, manual, or inspection documents uploaded yet.</p>}<p className="field-note">Equipment files use one-hour signed links from the private equipment-files bucket; they are never public URLs.</p></article>
      </section>
      <section className="equipment-workspace-grid"><section className="form-panel"><h2><Truck size={18} />Assign equipment</h2><AssignmentForm asset={asset} canOverride={canOverride} events={options.events} jobs={options.jobs} users={options.users} /></section><section className="form-panel"><h2><Gauge size={18} />Add reading</h2><ReadingForm asset={asset} /></section><section className="form-panel"><h2><Wrench size={18} />Maintenance schedule</h2><MaintenanceScheduleForm assetId={asset.id} /></section><section className="form-panel"><h2><ShieldCheck size={18} />Status and service control</h2><EquipmentStatusForm asset={asset} /></section><section className="form-panel wide-detail-panel"><h2><FileText size={18} />Upload private document</h2><EquipmentDocumentForm assetId={asset.id} /></section></section>
      <section className="notice-panel equipment-archive-panel"><div><strong>Archive equipment</strong><p>Archiving removes the asset from active fleet views but preserves assignments, readings, inspections, repairs, documents, and activity history.</p></div><form action={archiveEquipment}><input name="asset_id" type="hidden" value={asset.id} /><button className="secondary-action" type="submit"><Archive size={17} />Archive equipment</button></form></section>
    </>}
  </div></PlatformFrame>;
}

function PanelTitle({ icon, title: value }: { icon: React.ReactNode; title: string }) { return <h2 className="panel-title">{icon}{value}</h2>; }
function Row({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <article><small>{label}</small><strong>{value}</strong></article>; }
function title(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
function byNewest<K extends string>(key: K) { return (left: Record<K, string>, right: Record<K, string>) => new Date(right[key]).getTime() - new Date(left[key]).getTime(); }
function dueLabel(schedule: { next_due_at: string | null; next_due_mileage: number | null; next_due_hours: number | null }, mileage: number | null, hours: number | null) { const details = [schedule.next_due_at && `Due ${formatDate(schedule.next_due_at)}`, schedule.next_due_mileage != null && `${schedule.next_due_mileage.toLocaleString()} mi`, schedule.next_due_hours != null && `${schedule.next_due_hours.toLocaleString()} hr`].filter(Boolean); const overdue = (schedule.next_due_at && new Date(schedule.next_due_at) <= new Date()) || (schedule.next_due_mileage != null && mileage != null && mileage >= schedule.next_due_mileage) || (schedule.next_due_hours != null && hours != null && hours >= schedule.next_due_hours); return `${overdue ? "Due now · " : ""}${details.join(" · ") || "Interval based"}`; }
function DataWarning({ message }: { message: string }) { return <section className="data-warning"><strong>Database notice</strong><p>{message}</p></section>; }
