import SwiftUI

struct InvoiceDetailView: View {
    let invoiceID: String; let access: AppAccess; let fieldService: any FieldDataService; let photoService: any JobPhotoService
    @State private var payload: MobileInvoicePayload?; @State private var loading = true; @State private var stale = false; @State private var error: String?; @State private var showPayment = false
    var body: some View { Group { if loading && payload == nil { ProgressView("Loading invoice") } else if let payload { content(payload) } else { VStack(spacing: 10) { Image(systemName: "doc.plaintext").font(.largeTitle).foregroundStyle(.secondary); Text("Invoice unavailable").font(.headline); Text(error ?? "Try again.").foregroundStyle(.secondary) }.padding() } }
        .background(AngelTreeTheme.canvas).navigationTitle("Invoice").navigationBarTitleDisplayMode(.inline).task { await load(cached: true) }
        .sheet(isPresented: $showPayment) { if let payload { NavigationStack { ManualPaymentView(invoice: payload.invoice, fieldService: fieldService) { updated in self.payload = updated; showPayment = false } } } }
    }
    private func content(_ payload: MobileInvoicePayload) -> some View { let invoice = payload.invoice; return List {
        if stale { Section { Label("Showing saved invoice details", systemImage: "icloud.slash").foregroundStyle(AngelTreeTheme.warning) } }
        Section { LabeledContent("Invoice", value: invoice.invoiceNumber.map { "#\($0)" } ?? "Draft"); LabeledContent("Status", value: title(invoice.status)); if let party = invoice.party { NavigationLink { CustomerDetailView(reference: .init(id: party.id, kind: party.kind, name: party.name, contactName: nil, email: nil, phone: nil, address: invoice.serviceLocation.fullAddress), access: access, fieldService: fieldService, photoService: photoService) } label: { LabeledContent("Contracting party", value: party.name) } }; LabeledContent("Service location", value: invoice.serviceLocation.fullAddress); LabeledContent("Customer payment", value: invoice.customerPayable ? "Available" : "Not available"); LabeledContent("Portal", value: invoice.portalStatus.capitalized) }
        Section("Invoice lines") { ForEach(invoice.lines) { line in VStack(alignment: .leading, spacing: 6) { HStack(alignment: .firstTextBaseline) { Text(line.name).font(.headline); Spacer(); Text(money(line.totalCents)).font(.headline).foregroundStyle(AngelTreeTheme.forest) }; if let description = line.description { Text(description).font(.subheadline).foregroundStyle(.secondary) }; if line.quantity != 1 { Text("\(line.quantity.formatted()) × \(money(line.unitPriceCents)) each").font(.caption).foregroundStyle(.secondary) } }.padding(.vertical, 5) }; LabeledContent("Total", value: money(invoice.totalCents)); LabeledContent("Balance due") { Text(money(invoice.balanceDueCents)).font(.title3.bold()).foregroundStyle(AngelTreeTheme.forest) } }
        Section("Dates") { LabeledContent("Created", value: date(invoice.createdAt)); if let sent = invoice.sentAt { LabeledContent("Sent", value: date(sent)) }; if let due = invoice.dueAt { LabeledContent("Due", value: date(due)) }; if let paid = invoice.paidAt { LabeledContent("Paid", value: date(paid)) } }
        Section("Payments") { if invoice.payments.isEmpty { Text("No recorded payments.").foregroundStyle(.secondary) } else { ForEach(invoice.payments) { payment in VStack(alignment: .leading, spacing: 4) { HStack { Text(money(payment.amountCents)).font(.headline); Spacer(); Text(title(payment.status)).font(.caption) }; Text("\(title(payment.method ?? payment.source)) · \(payment.paidAt.map(date) ?? "Date unavailable")").font(.subheadline).foregroundStyle(.secondary); if let reference = payment.reference { Text("Reference: \(reference)").font(.caption).foregroundStyle(.secondary) } }.padding(.vertical, 4) } } }
        if !invoice.activity.isEmpty { Section("Recent activity") { ForEach(invoice.activity.prefix(8)) { event in LabeledContent(title(event.eventType), value: date(event.createdAt)) } } }
        Section("Actions") { if access.canRecordManualPayments && payload.canRecordPayments && invoice.canRecordManualPayment { Button { showPayment = true } label: { Label("Record manual payment", systemImage: "banknote") } }; if let job = invoice.linkedJobId { NavigationLink { JobDetailView(jobID: job, summary: nil, scheduleItem: nil, access: access, fieldService: fieldService, photoService: photoService) } label: { Label("Open linked job", systemImage: "leaf") } }; if let quote = invoice.linkedQuoteId { NavigationLink { ProposalDetailView(quoteID: quote, access: access, fieldService: fieldService, photoService: photoService) } label: { Label("Open linked proposal", systemImage: "doc.text") } }; if invoice.reminderEligible { Label("Payment reminder available in the full CRM", systemImage: "bell") .foregroundStyle(.secondary) } }
        if let error { Section { Text(error).foregroundStyle(.red) } }
    }.scrollContentBackground(.hidden) }
    private func load(cached: Bool) async { loading = true; do { let result = try await fieldService.invoiceDetail(id: invoiceID, userID: access.userID, allowCached: cached); payload = result.payload; stale = result.cached; error = nil; if result.cached { await load(cached: false) } } catch { self.error = (error as? LocalizedError)?.errorDescription ?? "Try again." }; loading = false }
    private func money(_ cents: Int) -> String { (Double(cents) / 100).formatted(.currency(code: "USD")) }; private func date(_ value: String) -> String { CRMDateParser.date(from: value).map(BusinessCalendar.dayHeading) ?? value }; private func title(_ value: String) -> String { value.replacingOccurrences(of: "_", with: " ").capitalized }
}

private struct ManualPaymentView: View {
    let invoice: MobileInvoiceDetail; let fieldService: any FieldDataService; let onSaved: (MobileInvoicePayload) -> Void
    @Environment(\.dismiss) private var dismiss; @State private var amount = ""; @State private var method = "check"; @State private var received = Date(); @State private var reference = ""; @State private var notes = ""; @State private var saving = false; @State private var error: String?
    var body: some View { Form { Section { LabeledContent("Remaining balance", value: money(invoice.balanceDueCents)); TextField("Payment amount", text: $amount).keyboardType(.decimalPad); Picker("Method", selection: $method) { Text("Check").tag("check"); Text("Cash").tag("cash"); Text("ACH").tag("ach"); Text("Other").tag("other") }; DatePicker("Received", selection: $received, displayedComponents: .date); TextField("Reference or check number", text: $reference); TextField("Internal note", text: $notes, axis: .vertical).lineLimit(2...5) }; if let error { Section { Text(error).foregroundStyle(.red) } } }
        .navigationTitle("Record Payment").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() }.disabled(saving) }; ToolbarItem(placement: .confirmationAction) { Button(saving ? "Recording…" : "Record") { Task { await save() } }.disabled(saving) } } }
    private func save() async { guard let decimal = Decimal(string: amount), decimal > 0 else { error = "Enter a valid amount."; return }; let cents = NSDecimalNumber(decimal: decimal * 100).rounding(accordingToBehavior: NSDecimalNumberHandler(roundingMode: .plain, scale: 0, raiseOnExactness: false, raiseOnOverflow: false, raiseOnUnderflow: false, raiseOnDivideByZero: false)).intValue; guard cents <= invoice.balanceDueCents else { error = "Payment cannot exceed the remaining balance."; return }; saving = true; defer { saving = false }; do { onSaved(try await fieldService.recordManualPayment(invoiceID: invoice.id, input: .init(amountCents: cents, method: method, receivedAt: ISO8601DateFormatter().string(from: received), reference: reference.isEmpty ? nil : reference, notes: notes.isEmpty ? nil : notes))) } catch { self.error = (error as? LocalizedError)?.errorDescription ?? "Payment was not recorded." } }
    private func money(_ cents: Int) -> String { (Double(cents) / 100).formatted(.currency(code: "USD")) }
}
