import SwiftUI

struct InvoicesView: View {
    let access: AppAccess; let fieldService: any FieldDataService; let photoService: any JobPhotoService
    @StateObject private var store: InvoiceDirectoryStore; @State private var scope: MobileInvoiceScope = .outstanding; @State private var query = ""
    init(access: AppAccess, fieldService: any FieldDataService, photoService: any JobPhotoService) { self.access = access; self.fieldService = fieldService; self.photoService = photoService; _store = StateObject(wrappedValue: InvoiceDirectoryStore(service: fieldService, userID: access.userID)) }
    var body: some View { List { Section { Picker("Invoice status", selection: $scope) { ForEach(MobileInvoiceScope.allCases, id: \.self) { Text($0.label).tag($0) } }.pickerStyle(.segmented) }; if normalized.isEmpty { directory } else { search } }
        .navigationTitle("Invoices").searchable(text: $query, prompt: "Invoice, customer, or address").scrollContentBackground(.hidden).background(AngelTreeTheme.canvas)
        .safeAreaInset(edge: .top) { if store.stale { Text("Showing saved invoices. Pull to refresh.").font(.caption.weight(.semibold)).foregroundStyle(AngelTreeTheme.warning).frame(maxWidth: .infinity).padding(8).background(AngelTreeTheme.canvas) } }
        .task(id: scope) { query = ""; store.clearSearch(); await store.load(scope) }.task(id: query) { await updateSearch() }.refreshable { await store.refresh(scope) }
    }
    @ViewBuilder private var directory: some View { if store.loading && store.results.isEmpty { Section { ProgressView("Loading invoices") } } else if let error = store.error, store.results.isEmpty { Section { retry(error) { await store.load(scope, force: true) } } } else if store.results.isEmpty { Section { empty("No \(scope.label.lowercased()) invoices") } } else { Section(scope.label) { ForEach(store.results) { invoice in row(invoice).task { await store.loadMoreIfNeeded(invoice, scope: scope) } } }; if store.loadingMore { Section { ProgressView("Loading more") } } } }
    @ViewBuilder private var search: some View { if normalized.count < 2 { Section { Text("Enter at least 2 characters to search.").foregroundStyle(.secondary) } } else if store.searching { Section { ProgressView("Searching invoices") } } else if let error = store.searchError { Section { retry(error) { await store.search(normalized, scope: scope) } } } else if store.searchResults.isEmpty { Section { empty("No matching invoices") } } else { Section("Results") { ForEach(store.searchResults) { row($0) } } } }
    private func row(_ invoice: MobileInvoiceDirectoryItem) -> some View { NavigationLink { InvoiceDetailView(invoiceID: invoice.id, access: access, fieldService: fieldService, photoService: photoService) } label: { VStack(alignment: .leading, spacing: 6) { HStack { Text(invoice.invoiceNumber.map { "Invoice #\($0)" } ?? "Draft invoice").font(.headline); Spacer(); Text(money(invoice.balanceDueCents)).font(.headline).foregroundStyle(invoice.balanceDueCents > 0 ? AngelTreeTheme.forest : .secondary) }; Text(invoice.party?.name ?? "Unknown contracting party").font(.subheadline.weight(.semibold)); Label(invoice.serviceLocation.fullAddress, systemImage: "mappin.and.ellipse").font(.caption).foregroundStyle(.secondary).lineLimit(2); HStack { StatusBadge(status: invoice.status, label: invoice.status.replacingOccurrences(of: "_", with: " ").capitalized); Spacer(); if let due = invoice.dueAt { Text("Due \(date(due))").font(.caption).foregroundStyle(.secondary) } }; if invoice.balanceDueCents != invoice.totalCents { Text("Total \(money(invoice.totalCents))").font(.caption).foregroundStyle(.secondary) } }.padding(.vertical, 5) } }
    private var normalized: String { query.trimmingCharacters(in: .whitespacesAndNewlines) }
    private func updateSearch() async { guard normalized.count >= 2 else { store.clearSearch(); return }; try? await Task.sleep(for: .milliseconds(350)); guard !Task.isCancelled else { return }; await store.search(normalized, scope: scope) }
    private func empty(_ title: String) -> some View { VStack(alignment: .leading, spacing: 4) { Text(title).font(.headline); Text("Pull to refresh or choose another status.").font(.subheadline).foregroundStyle(.secondary) }.padding(.vertical, 8) }
    private func retry(_ message: String, action: @escaping () async -> Void) -> some View { VStack(alignment: .leading, spacing: 8) { Text(message).foregroundStyle(.secondary); Button("Try again") { Task { await action() } }.buttonStyle(.bordered) } }
    private func money(_ cents: Int) -> String { (Double(cents) / 100).formatted(.currency(code: "USD")) }; private func date(_ value: String) -> String { CRMDateParser.date(from: value).map(BusinessCalendar.dayHeading) ?? value }
}
