import Link from "next/link";
import { Activity, AlertTriangle, Archive, Award, CheckCircle2, Clock3, FileText, KeyRound, Pencil, ShieldCheck, Truck, UserCheck, UsersRound } from "lucide-react";
import { CredentialForm, EmployeeDocumentForm, EmployeeRolesForm, OnboardingItemForm } from "../EmployeeForms";
import { archiveEmployee, markEmployeeInactive, reviewEmployeeDocument, reviewEmployeeRequest, startEmployeeOnboarding, updateSeparationItem, verifyEmployeeCredential } from "../actions";
import { EmployeePasswordResetForm } from "@/components/employee-password-reset-form";
import { PlatformFrame } from "@/components/PlatformFrame";
import { SetupRequired } from "@/components/SetupRequired";
import { getAuthenticatedPlatformContext } from "@/lib/auth/pageContext";
import { hasAllowedRole, platformRoleGroups } from "@/lib/auth/roles";
import { getEmployeeDetail, getEmployeeFormOptions } from "@/lib/data/employees";
import type { EmployeeCredential } from "@/lib/types/database";

type Props = { params: Promise<{ employeeId: string }>; searchParams: Promise<{ created?: string; updated?: string }> };
export default async function EmployeeDetailPage({ params, searchParams }: Props) {
  const { employeeId } = await params; const query = await searchParams; const context = await getAuthenticatedPlatformContext(`/admin/employees/${employeeId}`);
  if (!context.configured) return <SetupRequired title="Configure Supabase before opening employee records" />;
  const canAdmin = hasAllowedRole(context.roles, platformRoleGroups.accessApproval);
  const [detailResult, options] = await Promise.all([getEmployeeDetail(employeeId, canAdmin), getEmployeeFormOptions()]); const detail = detailResult.data; const employee = detail?.employee;
  return <PlatformFrame active="employees" roles={context.roles} userEmail={context.user.email}><div className="shell app-content employee-detail-page"><Link className="crew-back-link" href="/admin/employees">Back to employees</Link>{[detailResult.error, options.error].filter(Boolean).map((message) => <DataWarning key={message} message={message ?? ""} />)}{query.created ? <p className="form-message success">Employee record created.</p> : null}{query.updated ? <p className="form-message success">Employee changes saved.</p> : null}{!employee || !detail ? <section className="empty-state"><h2>Employee not found</h2><p>This record is unavailable.</p></section> : <>
    <section className="page-heading commerce-heading"><div><p className="surface-label"><UsersRound size={17} />{employee.employee_number || "Employee record"}</p><h1>{employee.preferred_name || employee.legal_name || "Employee"}</h1><p>{employee.job_title || "Job title not set"}{employee.crew_name ? ` · ${employee.crew_name}` : ""}</p></div><div className="action-row"><span className={`employee-status status-${employee.employment_status}`}>{title(employee.employment_status)}</span>{canAdmin ? <Link className="primary-action" href={`/admin/employees/${employee.id}/edit`}><Pencil size={18} />Edit employee</Link> : null}</div></section>
    {employee.profiles?.email && employee.contact_email && employee.profiles.email.toLowerCase() !== employee.contact_email.toLowerCase() ? <section className="employee-warning-banner"><AlertTriangle size={21} /><div><strong>Contact and login emails differ</strong><p>Contact: {employee.contact_email}. Login: {employee.profiles.email}. Editing this record does not silently change Supabase Auth.</p></div></section> : null}
    <section className="employee-metric-grid"><Metric label="Onboarding" value={`${progress(employee.employee_onboarding_items ?? [])}%`} /><Metric label="Platform access" value={employee.auth_user_id ? "Linked" : "Not linked"} /><Metric label="Time clock" value={detail.timeClockEnabled ? "Enabled" : "Disabled"} /><Metric label="Scheduling" value={schedulingEligibility(employee.employment_status, employee.is_active)} /><Metric label="Credentials" value={credentialSummary(employee.employee_credentials ?? [])} /></section>
    <section className="employee-action-ribbon">{employee.employment_status !== "onboarding" && canAdmin ? <form action={startEmployeeOnboarding}><input name="employee_id" type="hidden" value={employee.id} /><button type="submit"><UserCheck size={18} />Start onboarding</button></form> : <Link href="#onboarding"><UserCheck size={18} />Onboarding</Link>}<Link href="#credentials"><Award size={18} />Add credential</Link><Link href="#documents"><FileText size={18} />Upload document</Link><Link href="/admin/training"><UsersRound size={18} />Record training</Link><Link href="/admin/equipment"><Truck size={18} />Assign equipment/PPE</Link>{employee.auth_user_id ? <Link href={`/admin/time/${employee.auth_user_id}`}><Clock3 size={18} />Timer access</Link> : <Link href="/admin/access"><ShieldCheck size={18} />Approve access</Link>}</section>
    <section className="detail-grid"><article className="detail-panel"><PanelTitle icon={<UserCheck size={18} />} title="Contact and employment" /><dl className="crew-detail-list"><Row label="Legal name" value={employee.legal_name || "Not set"} /><Row label="Contact email" value={employee.contact_email || "Not set"} /><Row label="Phone" value={employee.contact_phone || "Not set"} /><Row label="Home address" value={employee.home_address || "Not set"} /><Row label="Hire date" value={employee.hire_date ? formatDate(employee.hire_date) : "Not set"} /><Row label="Employment type" value={employee.employment_type ? title(employee.employment_type) : "Not set"} /><Row label="Supervisor" value={employee.supervisor?.preferred_name || employee.supervisor?.legal_name || "Not assigned"} /></dl></article>
      <article className="detail-panel"><PanelTitle icon={<KeyRound size={18} />} title="Platform access" /><p>{employee.auth_user_id ? `Linked to ${employee.profiles?.email || "platform account"}.` : "No platform account is linked. Employment history can remain without login access."}</p><div className="filter-pills">{detail.roles.length ? detail.roles.map((role) => <span key={role}>{title(role)}</span>) : <span>No role</span>}</div>{canAdmin && employee.auth_user_id ? <EmployeeRolesForm authUserId={employee.auth_user_id} employeeId={employee.id} roles={detail.roles} /> : null}{canAdmin && employee.auth_user_id && employee.profiles ? <EmployeePasswordResetForm users={[{ ...employee.profiles, role_names: detail.roles }]} /> : null}</article>
      <article className="detail-panel"><PanelTitle icon={<ShieldCheck size={18} />} title="Emergency contact" />{employee.employee_emergency_contacts?.length ? employee.employee_emergency_contacts.map((contact) => <dl className="crew-detail-list" key={contact.id}><Row label="Name" value={contact.full_name} /><Row label="Relationship" value={contact.relationship || "Not set"} /><Row label="Phone" value={contact.phone} /></dl>) : <p className="inline-empty">Emergency contact is incomplete.</p>}</article>
      <article className="detail-panel"><PanelTitle icon={<Truck size={18} />} title="Issued equipment and PPE" />{detail.equipmentAssignments.length ? detail.equipmentAssignments.map((assignment: any) => <Link className="linked-record" href={`/admin/equipment/${assignment.asset_id}`} key={assignment.id}><strong>{assignment.equipment_assets?.name || "Equipment"}</strong><span>{assignment.equipment_assets?.asset_number || "Asset"} · {assignment.returned_at ? "Returned" : "Issued"}</span></Link>) : <p className="inline-empty">No equipment or PPE assignment history.</p>}</article>
    </section>
    <section className="panel employee-onboarding-panel" id="onboarding"><div className="panel-header"><h2>Onboarding checklist</h2><span>{progress(employee.employee_onboarding_items ?? [])}% complete</span></div><div className="employee-checklist">{employee.employee_onboarding_items?.slice().sort((a,b) => a.sort_order-b.sort_order).map((item) => <OnboardingItemForm employeeId={employee.id} item={item} key={item.id} />)}</div></section>
    <section className="employee-workspace-grid"><section className="panel" id="credentials"><div className="panel-header"><h2>Credentials and licenses</h2><span>Uploads remain pending until staff verifies them.</span></div><div className="linked-record-list">{employee.employee_credentials?.length ? employee.employee_credentials.map((credential) => <article className={`linked-record credential-row ${credentialTone(credential)}`} key={credential.id}><strong>{credential.credential_types?.label || "Credential"}</strong><span>{credentialDisplayStatus(credential)}{credential.expiration_date ? ` · ${formatDate(credential.expiration_date)}` : ""}</span>{credential.status === "pending_verification" ? <form action={verifyEmployeeCredential}><input name="employee_id" type="hidden" value={employee.id} /><input name="credential_id" type="hidden" value={credential.id} /><button className="secondary-action" type="submit"><CheckCircle2 size={16} />Verify credential</button></form> : null}</article>) : <p className="inline-empty">No credentials recorded.</p>}</div><CredentialForm canAdmin={canAdmin} employeeId={employee.id} types={options.credentialTypes} /></section>
      <section className="panel" id="documents"><div className="panel-header"><h2>Private documents</h2><span>Files open through short-lived signed links.</span></div>{employee.employee_documents?.length ? employee.employee_documents.map((document) => <article className="linked-record" key={document.id}><strong>{document.title}</strong><span>{title(document.access_classification)} · {title(document.review_status)}{document.expiration_date ? ` · expires ${formatDate(document.expiration_date)}` : ""}</span>{document.signed_url ? <a className="secondary-action" href={document.signed_url} rel="noreferrer" target="_blank">Open private file</a> : null}{document.review_status === "pending" ? <form action={reviewEmployeeDocument} className="document-review-inline"><input name="employee_id" type="hidden" value={employee.id} /><input name="document_id" type="hidden" value={document.id} /><input name="review_notes" placeholder="Review note" /><button name="review_status" type="submit" value="approved">Approve</button><button name="review_status" type="submit" value="rejected">Reject</button></form> : null}</article>) : <p className="inline-empty">No employee documents.</p>}<EmployeeDocumentForm canOwnerOnly={canAdmin} employeeId={employee.id} /></section>
    </section>
    <section className="detail-grid"><article className="detail-panel"><PanelTitle icon={<UsersRound size={18} />} title="Training history" />{employee.training_attendees?.length ? employee.training_attendees.map((attendee) => <article className="linked-record" key={attendee.id}><strong>{attendee.training_sessions?.title || "Training"}</strong><span>{title(attendee.result)} · {attendee.training_sessions?.starts_at ? formatDate(attendee.training_sessions.starts_at) : "Date unavailable"}</span></article>) : <p className="inline-empty">No training recorded.</p>}<Link className="secondary-action" href="/admin/training">Record training</Link></article>
      <article className="detail-panel"><PanelTitle icon={<ShieldCheck size={18} />} title="Safety meetings" />{employee.safety_meeting_attendees?.length ? employee.safety_meeting_attendees.map((attendee) => <article className="linked-record" key={attendee.id}><strong>{attendee.safety_meetings?.title || "Safety meeting"}</strong><span>{title(attendee.attendance_status)} · {attendee.acknowledged_at ? "Acknowledged" : "Acknowledgment pending"}</span></article>) : <p className="inline-empty">No safety meeting history.</p>}<Link className="secondary-action" href="/admin/safety">Record safety meeting</Link></article>
      <article className="detail-panel"><PanelTitle icon={<AlertTriangle size={18} />} title="Employee requests" />{employee.employee_requests?.length ? employee.employee_requests.map((request) => <article className="linked-record" key={request.id}><strong>{request.title}</strong><span>{title(request.request_type)} · {title(request.status)}</span>{request.status === "pending" ? <form action={reviewEmployeeRequest} className="document-review-inline"><input name="employee_id" type="hidden" value={employee.id} /><input name="request_id" type="hidden" value={request.id} /><input name="review_notes" placeholder="Review note" /><button name="status" type="submit" value="approved">Approve</button><button name="status" type="submit" value="rejected">Reject</button></form> : null}</article>) : <p className="inline-empty">No employee correction or training requests.</p>}</article>
      <article className="detail-panel"><PanelTitle icon={<Activity size={18} />} title="Activity history" />{detail.activity.length ? detail.activity.map((event: any) => <article className="linked-record" key={event.id}><strong>{title(event.event_type)}</strong><span>{formatDateTime(event.created_at)}</span></article>) : <p className="inline-empty">No employee activity recorded yet.</p>}</article>
    </section>
    {employee.employee_separation_items?.length ? <section className="panel employee-separation-panel"><div className="panel-header"><div><h2>Separation checklist</h2><p>Historical records stay intact while return, access, schedule, and time review are completed deliberately.</p></div></div><div className="employee-checklist">{employee.employee_separation_items.map((item) => <form action={updateSeparationItem} className="employee-checklist-row" key={item.id}><input name="employee_id" type="hidden" value={employee.id} /><input name="item_id" type="hidden" value={item.id} /><div><strong>{item.label}</strong><small>{item.completed_at ? `Completed ${formatDate(item.completed_at)}` : "Needs review"}</small></div><select defaultValue={item.completion_status} name="completion_status"><option value="incomplete">Incomplete</option><option value="complete">Complete</option><option value="not_applicable">Not applicable</option></select><input defaultValue={item.notes ?? ""} name="notes" placeholder="Review note" /><button type="submit">Update</button></form>)}</div></section> : null}
    {canAdmin ? <section className="notice-panel employee-admin-controls"><div><strong>Inactive and archive controls</strong><p>These controls preserve all employment, time, job, training, acknowledgment, credential, and equipment history. Future schedule assignments are left for explicit staff review.</p></div><form action={markEmployeeInactive} className="inline-admin-form"><input name="employee_id" type="hidden" value={employee.id} /><input name="reason" placeholder="Required reason" required /><button className="secondary-action" type="submit">Mark inactive</button></form><form action={archiveEmployee}><input name="employee_id" type="hidden" value={employee.id} /><button className="secondary-action" type="submit"><Archive size={16} />Archive employee</button></form></section> : null}
  </>}</div></PlatformFrame>;
}
function PanelTitle({ icon, title: label }: { icon: React.ReactNode; title: string }) { return <h2 className="panel-title">{icon}{label}</h2>; } function Row({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; } function Metric({ label, value }: { label: string; value: string }) { return <article><small>{label}</small><strong>{value}</strong></article>; }
function progress(items: { completion_status: string }[]) { return items.length ? Math.round(items.filter((item) => item.completion_status !== "incomplete").length / items.length * 100) : 0; }
function credentialDisplayStatus(credential: EmployeeCredential) { if (credential.status !== "active") return title(credential.status); if (credential.expiration_date && new Date(credential.expiration_date) < new Date()) return "Expired"; const warningDays = credential.credential_types?.default_warning_days ?? 30; if (credential.expiration_date && new Date(credential.expiration_date) <= new Date(Date.now() + warningDays*86400000)) return `Expiring within ${warningDays} days`; return "Active"; }
function credentialTone(credential: EmployeeCredential) { const status = credentialDisplayStatus(credential); return status === "Expired" ? "danger" : status.startsWith("Expiring") || status === "Pending Verification" ? "warning" : "success"; }
function credentialSummary(credentials: EmployeeCredential[]) { const expired = credentials.filter((credential) => credential.expiration_date && new Date(credential.expiration_date) < new Date()).length; return expired ? `${expired} expired` : `${credentials.filter((credential) => credential.status === "active").length} active`; }
function schedulingEligibility(status: string, isActive: boolean) { if (!isActive || ["inactive", "separated", "leave"].includes(status)) return "Override required"; if (["applicant", "onboarding"].includes(status)) return "Review needed"; return "Normally eligible"; }
function title(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); } function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); } function formatDateTime(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); } function DataWarning({ message }: { message: string }) { return <section className="data-warning"><strong>Database notice</strong><p>{message}</p></section>; }
