"use client";

import { useReliableActionState } from "@/hooks/use-reliable-action-state";
import { CircleDollarSign, Plus, ReceiptText, Save, Settings2 } from "lucide-react";
import { addJobCost, addLaborCostRate, saveReportingSettings, type ReportingActionState } from "@/lib/actions/reporting";
import type { ReportingSettings } from "@/lib/types/database";

const initialState: ReportingActionState = { status: "idle", message: "" };

export function JobCostEntryForm({ approveByDefault = false, jobId }: { approveByDefault?: boolean; jobId: string }) {
  const [state, action, pending] = useReliableActionState(addJobCost, initialState);
  return <form action={action} className="reporting-input-form"><input name="job_id" type="hidden" value={jobId} /><div className="reporting-input-heading"><ReceiptText size={18} /><div><strong>Add direct job cost</strong><span>Private operational cost; never shown on customer documents.</span></div></div>{state.message ? <p className={`form-message ${state.status}`} role={state.status === "error" ? "alert" : "status"}>{state.message}</p> : null}<div className="reporting-input-grid"><label>Category<select name="category" required><option value="materials">Materials</option><option value="disposal">Disposal / dump fee</option><option value="subcontractor">Subcontractor</option><option value="equipment_rental">Equipment rental</option><option value="crane">Crane</option><option value="fuel">Fuel</option><option value="permit">Permit</option><option value="travel">Travel</option><option value="other">Other</option></select></label><label>Amount<input inputMode="decimal" min="0" name="amount" placeholder="0.00" required step="0.01" /></label><label>Date<input defaultValue={new Date().toISOString().slice(0, 10)} name="incurred_on" required type="date" /></label><label>Vendor<input name="vendor_name" placeholder="Optional" /></label></div><label>Description<input name="description" placeholder="Mulch, dump fee, crane rental..." required /></label><label>Receipt<input accept="image/jpeg,image/png,image/webp,application/pdf" name="receipt" type="file" /><small>Private JPG, PNG, WebP, or PDF, up to 10 MB.</small></label><label>Notes<textarea name="notes" rows={2} /></label>{approveByDefault ? <label className="reporting-checkbox"><input defaultChecked name="approve_now" type="checkbox" />Approve this cost now</label> : <p className="reporting-form-note">Crew submissions remain pending until office review.</p>}<button disabled={pending} type="submit"><Plus size={17} />{pending ? "Saving..." : approveByDefault ? "Add cost" : "Submit cost"}</button></form>;
}

export function LaborCostRateForm({ employees }: { employees: { id: string; preferred_name: string | null; legal_name: string | null }[] }) {
  const [state, action, pending] = useReliableActionState(addLaborCostRate, initialState);
  return <form action={action} className="reporting-input-form"><div className="reporting-input-heading"><CircleDollarSign size={18} /><div><strong>Add historical labor cost</strong><span>Restricted operational estimate. Existing rates are preserved.</span></div></div>{state.message ? <p className={`form-message ${state.status}`}>{state.message}</p> : null}<div className="reporting-input-grid"><label>Employee<select name="employee_id" required><option value="">Choose employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.preferred_name || employee.legal_name || "Employee"}</option>)}</select></label><label>Hourly cost<input inputMode="decimal" min="0" name="hourly_cost" placeholder="0.00" required step="0.01" /></label><label>Effective from<input name="effective_from" required type="date" /></label><label>Effective through<input name="effective_to" type="date" /></label><label>Burden %<input inputMode="decimal" max="500" min="0" name="burden_percent" step="0.001" /></label></div><label>Notes<textarea name="notes" rows={2} /></label><button disabled={pending} type="submit"><Plus size={17} />{pending ? "Adding..." : "Add rate"}</button></form>;
}

export function ReportingSettingsForm({ settings }: { settings: ReportingSettings }) {
  const [state, action, pending] = useReliableActionState(saveReportingSettings, initialState);
  return <form action={action} className="reporting-input-form"><div className="reporting-input-heading"><Settings2 size={18} /><div><strong>Reporting settings</strong><span>Owner/admin controlled thresholds and cost defaults.</span></div></div>{state.message ? <p className={`form-message ${state.status}`}>{state.message}</p> : null}<div className="reporting-input-grid"><label>Business timezone<input defaultValue={settings.business_timezone} name="business_timezone" required /></label><label>Lead stale after days<input defaultValue={settings.lead_stale_business_days} min="1" name="lead_stale_business_days" type="number" /></label><label>Draft quote stale after days<input defaultValue={settings.draft_quote_stale_days} min="1" name="draft_quote_stale_days" type="number" /></label><label>Sent quote stale after days<input defaultValue={settings.sent_quote_stale_days} min="1" name="sent_quote_stale_days" type="number" /></label><label>Default labor burden %<input defaultValue={settings.default_labor_burden_percent ?? ""} max="500" min="0" name="default_labor_burden_percent" step="0.001" type="number" /></label><label>Blended hourly cost<input defaultValue={settings.blended_labor_cost_cents == null ? "" : (settings.blended_labor_cost_cents / 100).toFixed(2)} min="0" name="blended_labor_cost" step="0.01" type="number" /></label></div><p className="reporting-form-note">Leave blended cost blank to require employee-specific historical rates. No wage or overhead value is invented.</p><button disabled={pending} type="submit"><Save size={17} />{pending ? "Saving..." : "Save settings"}</button></form>;
}
