import Link from "next/link";
import { AlertTriangle, Boxes, Factory, MapPinned, PackageCheck, Plus, ReceiptText, Scale, Truck } from "lucide-react";
import {
  DeliveryForm,
  DisposalForm,
  InventoryLocationForm,
  InventoryMovementForm,
  MaterialCatalogForm,
  ProductionBatchForm,
  PurchaseForm,
  ReleaseReservationForm,
  ReservationForm,
  ReverseTransactionForm,
  StockpileMeasurementForm,
  TransactionCostReviewForm,
} from "@/components/materials-forms";
import { PlatformFrame } from "@/components/PlatformFrame";
import { SetupRequired } from "@/components/SetupRequired";
import { getAuthenticatedPlatformContext } from "@/lib/auth/pageContext";
import { formatMaterialQuantity, materialLabel } from "@/lib/materials/definitions";
import { getMaterialsWorkspace, type MaterialWorkspaceData } from "@/lib/data/materials";

type MaterialsPageProps = { searchParams: Promise<{ view?: string; q?: string; category?: string; location?: string }> };
const views = ["overview", "catalog", "movements", "reservations", "purchases", "disposal", "production", "deliveries"];

export default async function MaterialsPage({ searchParams }: MaterialsPageProps) {
  const query = await searchParams;
  const context = await getAuthenticatedPlatformContext("/admin/materials");
  if (!context.configured) return <SetupRequired title="Configure Supabase before opening materials" />;
  const data = await getMaterialsWorkspace(context.roles);
  const view = views.includes(query.view ?? "") ? query.view! : "overview";
  const filteredMaterials = data.materials.filter((material) => (!query.category || material.category === query.category) && (!query.q || [material.name, material.sku, material.description].some((value) => value?.toLowerCase().includes(query.q!.toLowerCase()))));

  return <PlatformFrame active="materials" roles={context.roles} userEmail={context.user.email}>
    <div className="shell app-content materials-page">
      <section className="page-heading commerce-heading"><div><p className="surface-label"><Boxes size={18} />Materials and inventory</p><h1>Materials</h1><p>Plan, reserve, receive, move, use, deliver, produce, and dispose of materials with an auditable stock history.</p></div><Link className="primary-action" href="/admin/materials?view=catalog#add-material"><Plus size={18} />Add material</Link></section>
      {data.error ? <section className="data-warning"><strong>Materials database notice</strong><p>{data.error}</p></section> : null}
      <nav className="materials-tabs" aria-label="Materials views">{views.map((item) => <Link aria-current={view === item ? "page" : undefined} href={`/admin/materials?view=${item}`} key={item}>{tabIcon(item)}{materialLabel(item)}</Link>)}</nav>
      {view === "overview" ? <Overview data={data} /> : null}
      {view === "catalog" ? <Catalog data={data} filteredMaterials={filteredMaterials} query={query} /> : null}
      {view === "movements" ? <Movements data={data} /> : null}
      {view === "reservations" ? <Reservations data={data} /> : null}
      {view === "purchases" ? <Purchases data={data} /> : null}
      {view === "disposal" ? <Disposal data={data} /> : null}
      {view === "production" ? <Production data={data} /> : null}
      {view === "deliveries" ? <Deliveries data={data} /> : null}
    </div>
  </PlatformFrame>;
}

function Overview({ data }: { data: MaterialWorkspaceData }) {
  const alerts = operationalAlerts(data);
  const totalAvailable = data.balances.reduce((sum, balance) => sum + Number(balance.available_quantity), 0);
  return <>
    <section className="materials-summary-grid" aria-label="Inventory summary"><Summary icon={<Boxes />} label="Active materials" value={data.materials.length} /><Summary icon={<MapPinned />} label="Inventory locations" value={data.locations.length} /><Summary icon={<Scale />} label="Available unit totals" value={Number(totalAvailable.toFixed(3))} note="Mixed units are not converted" /><Summary icon={<AlertTriangle />} label="Needs attention" tone={alerts.length ? "warning" : "success"} value={alerts.length} /></section>
    <section className="materials-overview-grid"><section className="materials-section"><SectionHeading icon={<AlertTriangle size={20} />} title="Operational attention" body="Shortages, missing paperwork, stale estimates, and due deliveries." />{alerts.length ? <div className="materials-alert-list">{alerts.map((alert) => <Link className={`materials-alert ${alert.tone}`} href={alert.href} key={alert.label}><strong>{alert.label}</strong><span>{alert.detail}</span></Link>)}</div> : <p className="form-message success">No material issues need attention right now.</p>}</section><section className="materials-section"><SectionHeading icon={<PackageCheck size={20} />} title="Recent movement" body="Latest immutable inventory entries." /><TransactionList data={data} limit={8} /></section></section>
    <section className="materials-section"><SectionHeading icon={<Scale size={20} />} title="Stock by material and location" body="Available equals on hand minus active reservations. Estimated bulk measurements remain labeled separately." /><StockTable data={data} /></section>
  </>;
}

function Catalog({ data, filteredMaterials, query }: { data: MaterialWorkspaceData; filteredMaterials: MaterialWorkspaceData["materials"]; query: { q?: string; category?: string } }) {
  return <><form className="materials-filter-bar" method="get"><input name="view" type="hidden" value="catalog" /><label>Search<input defaultValue={query.q ?? ""} name="q" placeholder="Name, SKU, description" /></label><label>Category<select defaultValue={query.category ?? ""} name="category"><option value="">All categories</option>{Array.from(new Set(data.materials.map((material) => material.category))).map((value) => <option key={value} value={value}>{materialLabel(value)}</option>)}</select></label><button className="secondary-action" type="submit">Apply filters</button></form>
    <section className="materials-catalog-layout"><section className="materials-section"><SectionHeading icon={<Boxes size={20} />} title="Material catalog" body="Stock-tracked and non-stock services use the same clear units without automatic conversions." /><div className="material-record-list">{filteredMaterials.length ? filteredMaterials.map((material) => { const balances = data.balances.filter((balance) => balance.material_id === material.id); const available = balances.reduce((sum, item) => sum + Number(item.available_quantity), 0); const cost = data.costs.find((item) => item.material_id === material.id); return <article className="material-record" key={material.id}><div><span className={`material-category category-${material.category}`}>{materialLabel(material.category)}</span><h2>{material.name}</h2><p>{material.description || "No description entered."}</p></div><dl><div><dt>Unit</dt><dd>{materialLabel(material.default_unit)}</dd></div><div><dt>Available</dt><dd>{material.stock_tracked ? formatMaterialQuantity(available, material.default_unit) : "Stock not tracked"}</dd></div><div><dt>Reorder at</dt><dd>{material.reorder_threshold == null ? "Not set" : formatMaterialQuantity(material.reorder_threshold, material.default_unit)}</dd></div>{data.canViewCosts ? <div><dt>Internal cost</dt><dd>{cost?.internal_unit_cost_cents == null ? "Not set" : money(cost.internal_unit_cost_cents)}</dd></div> : null}</dl><details className="material-edit-details"><summary>Edit material</summary><MaterialCatalogForm canViewCosts={data.canViewCosts} internalCostCents={cost?.internal_unit_cost_cents} material={material} organizations={data.organizations} /></details></article>; }) : <p className="inline-empty">No materials match these filters.</p>}</div></section><aside className="materials-side-stack"><section className="form-panel" id="add-material"><h2>Add material</h2><p>Choose the unit used in the field. The system will not make unsafe unit conversions.</p><MaterialCatalogForm canViewCosts={data.canViewCosts} organizations={data.organizations} /></section><section className="form-panel"><h2>Add inventory location</h2><InventoryLocationForm equipment={data.equipment} /></section></aside></section>
  </>;
}

function Movements({ data }: { data: MaterialWorkspaceData }) { return <section className="materials-workspace-grid"><section className="materials-section"><SectionHeading icon={<Truck size={20} />} title="Inventory ledger" body="History cannot be edited or deleted. Corrections create a linked reversal." /><TransactionList data={data} /></section><aside className="form-panel"><h2>Record movement</h2><p>Use From for outgoing stock, To for incoming stock, and both for transfers or loads.</p><InventoryMovementForm equipment={data.equipment} jobs={data.jobs} locations={data.locations} materials={data.materials} /></aside></section>; }
function Reservations({ data }: { data: MaterialWorkspaceData }) { const active = data.reservations.filter((reservation) => reservation.status === "active"); return <section className="materials-workspace-grid"><section className="materials-section"><SectionHeading icon={<PackageCheck size={20} />} title="Active reservations" body="Reservations reduce available quantity but leave on-hand stock unchanged." />{active.length ? <div className="material-record-list">{active.map((reservation) => <article className="material-record" key={reservation.id}><div><h2>{materialName(data, reservation.material_id)}</h2><p>{jobName(data, reservation.job_id)} from {locationName(data, reservation.location_id)}</p></div><strong>{formatMaterialQuantity(reservation.quantity, reservation.unit)}</strong><ReleaseReservationForm reservationId={reservation.id} /></article>)}</div> : <p className="inline-empty">No active reservations.</p>}</section><aside className="form-panel"><h2>Reserve material</h2><ReservationForm jobs={data.jobs} locations={data.locations} materials={data.materials} /></aside></section>; }
function Purchases({ data }: { data: MaterialWorkspaceData }) { return <section className="materials-workspace-grid"><section className="materials-section"><SectionHeading icon={<ReceiptText size={20} />} title="Purchases and receiving" body="Purchases update the current unit-cost reference; job cost is recognized later at approved job use." />{data.purchases.length ? <SimpleRows rows={data.purchases.map((purchase) => ({ title: purchase.vendor_name || organizationName(data, purchase.vendor_organization_id) || "Material purchase", detail: `${purchase.purchase_date} - received at ${locationName(data, purchase.received_location_id)}`, value: data.canViewCosts ? money(purchase.total_cents) : "Cost restricted" }))} /> : <p className="inline-empty">No purchases recorded.</p>}</section><aside className="form-panel">{data.canViewCosts ? <><h2>Record purchase</h2><PurchaseForm locations={data.locations} materials={data.materials} organizations={data.organizations} /></> : <><h2>Cost access required</h2><p>Purchases include vendor pricing and are limited to authorized financial roles.</p></>}</aside></section>; }
function Disposal({ data }: { data: MaterialWorkspaceData }) { return <section className="materials-workspace-grid"><section className="materials-section"><SectionHeading icon={<Truck size={20} />} title="Disposal and donation loads" body="Facility fees and receipts remain private; destination history stays linked to the work order." />{data.disposalRecords.length ? <SimpleRows rows={data.disposalRecords.map((record) => ({ title: record.destination_name, detail: `${materialLabel(record.destination_type)} - ${jobName(data, record.job_id)}${record.receipt_storage_path ? " - receipt attached" : " - no receipt"}`, value: record.quantity ? formatMaterialQuantity(record.quantity, record.unit, record.is_estimated) : materialLabel(record.status) }))} /> : <p className="inline-empty">No disposal loads recorded.</p>}</section><aside className="form-panel"><h2>Record disposal load</h2><DisposalForm equipment={data.equipment} jobs={data.jobs} locations={data.locations} materials={data.materials} showCosts={data.canViewCosts} /></aside></section>; }
function Production({ data }: { data: MaterialWorkspaceData }) { return <section className="materials-workspace-grid"><section className="materials-section"><SectionHeading icon={<Factory size={20} />} title="Production and stockpiles" body="Batch inputs and outputs post separate ledger movements. Visual and dimensions-based stockpile measurements are estimates." />{data.productionBatches.length ? <SimpleRows rows={data.productionBatches.map((batch) => ({ title: batch.batch_number, detail: `${materialName(data, batch.product_material_id)} - ${materialLabel(batch.status)}${batch.color ? ` - ${batch.color}` : ""}`, value: batch.estimated_output_quantity ? formatMaterialQuantity(batch.estimated_output_quantity, batch.output_unit, true) : "Output not entered" }))} /> : <p className="inline-empty">No production batches recorded.</p>}<h3>Recent stockpile measurements</h3>{data.stockpileMeasurements.length ? <SimpleRows rows={data.stockpileMeasurements.slice(0, 12).map((measurement) => ({ title: materialName(data, measurement.material_id), detail: `${locationName(data, measurement.location_id)} - ${materialLabel(measurement.measurement_method)}`, value: formatMaterialQuantity(measurement.quantity, measurement.unit, measurement.is_estimated) }))} /> : <p className="inline-empty">No stockpile measurements.</p>}</section><aside className="materials-side-stack"><section className="form-panel"><h2>Complete production batch</h2><p>Enter business records only. The platform does not recommend chemical mixing ratios.</p><ProductionBatchForm equipment={data.equipment} locations={data.locations} materials={data.materials} /></section><section className="form-panel"><h2>Measure stockpile</h2><StockpileMeasurementForm locations={data.locations} materials={data.materials} /></section></aside></section>; }
function Deliveries({ data }: { data: MaterialWorkspaceData }) { return <section className="materials-workspace-grid"><section className="materials-section"><SectionHeading icon={<Truck size={20} />} title="Customer deliveries" body="Customer-visible notes stay separate from internal instructions and proof files." />{data.deliveries.length ? <SimpleRows rows={data.deliveries.map((delivery) => ({ title: `${materialName(data, delivery.material_id)} to ${customerName(data, delivery.customer_id)}`, detail: `${materialLabel(delivery.status)}${delivery.delivery_window_start ? ` - ${formatDate(delivery.delivery_window_start)}` : ""}`, value: formatMaterialQuantity(delivery.quantity, delivery.unit) }))} /> : <p className="inline-empty">No customer deliveries.</p>}</section><aside className="form-panel"><h2>Schedule or complete delivery</h2><DeliveryForm customers={data.customers} equipment={data.equipment} jobs={data.jobs} locations={data.locations} materials={data.materials} /></aside></section>; }

function StockTable({ data }: { data: MaterialWorkspaceData }) { const rows = data.balances.map((balance) => ({ ...balance, material: data.materials.find((item) => item.id === balance.material_id), location: data.locations.find((item) => item.id === balance.location_id) })); return rows.length ? <div className="materials-table-wrap"><table className="materials-table"><thead><tr><th>Material</th><th>Location</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Latest movement</th></tr></thead><tbody>{rows.map((row) => <tr className={Number(row.available_quantity) < 0 ? "negative" : undefined} key={`${row.material_id}-${row.location_id}`}><td>{row.material?.name ?? "Unknown"}</td><td>{row.location?.name ?? "Unknown"}</td><td>{formatMaterialQuantity(row.on_hand_quantity, row.material?.default_unit ?? "each")}</td><td>{formatMaterialQuantity(row.reserved_quantity, row.material?.default_unit ?? "each")}</td><td><strong>{formatMaterialQuantity(row.available_quantity, row.material?.default_unit ?? "each")}</strong></td><td>{row.latest_transaction_at ? formatDate(row.latest_transaction_at) : "None"}</td></tr>)}</tbody></table></div> : <p className="inline-empty">No tracked stock yet. Receive material to establish a balance.</p>; }
function TransactionList({ data, limit = 150 }: { data: MaterialWorkspaceData; limit?: number }) { return data.transactions.length ? <div className="transaction-list">{data.transactions.slice(0, limit).map((transaction) => { const cost = data.transactionCosts.find((item) => item.transaction_id === transaction.id); return <article key={transaction.id}><div><span className={`transaction-type type-${transaction.transaction_type}`}>{materialLabel(transaction.transaction_type)}</span><strong>{materialName(data, transaction.material_id)}</strong><p>{locationName(data, transaction.source_location_id)} to {locationName(data, transaction.destination_location_id)}{transaction.job_id ? ` - ${jobName(data, transaction.job_id)}` : ""}</p>{cost?.costing_status === "pending" ? <TransactionCostReviewForm transactionId={transaction.id} /> : null}</div><div><strong>{formatMaterialQuantity(transaction.quantity, transaction.unit, transaction.is_estimated)}</strong><small>{formatDate(transaction.occurred_at)}</small>{cost ? <small>Cost: {cost.direct_cost_cents == null ? "unit cost missing" : `${money(cost.direct_cost_cents)} - ${materialLabel(cost.costing_status)}`}</small> : null}{data.canViewCosts && transaction.transaction_type !== "reversal" ? <ReverseTransactionForm transactionId={transaction.id} /> : null}</div></article>; })}</div> : <p className="inline-empty">No inventory movements recorded.</p>; }
function Summary({ icon, label, note, tone = "", value }: { icon: React.ReactNode; label: string; note?: string; tone?: string; value: number }) { return <article className={`materials-summary ${tone}`}><span>{icon}</span><strong>{value}</strong><p>{label}</p>{note ? <small>{note}</small> : null}</article>; }
function SectionHeading({ body, icon, title }: { body: string; icon: React.ReactNode; title: string }) { return <div className="materials-section-heading"><span>{icon}</span><div><h2>{title}</h2><p>{body}</p></div></div>; }
function SimpleRows({ rows }: { rows: { title: string; detail: string; value: string }[] }) { return <div className="material-simple-rows">{rows.map((row, index) => <article key={`${row.title}-${index}`}><div><strong>{row.title}</strong><span>{row.detail}</span></div><b>{row.value}</b></article>)}</div>; }
function operationalAlerts(data: MaterialWorkspaceData) { const now = Date.now(); const low = data.materials.filter((material) => material.stock_tracked && material.reorder_threshold != null && data.balances.filter((balance) => balance.material_id === material.id).reduce((sum, balance) => sum + Number(balance.available_quantity), 0) <= Number(material.reorder_threshold)); const negative = data.balances.filter((balance) => Number(balance.available_quantity) < 0); const missingReceipts = data.disposalRecords.filter((record) => record.status === "completed" && Number(record.fee_cents ?? 0) > 0 && !record.receipt_storage_path); const staleStockpiles = data.stockpileMeasurements.filter((measurement, index, records) => records.findIndex((candidate) => candidate.material_id === measurement.material_id && candidate.location_id === measurement.location_id) === index && now - new Date(measurement.measured_at).getTime() > 30 * 86400000); const dueDeliveries = data.deliveries.filter((delivery) => !["delivered", "cancelled"].includes(delivery.status) && delivery.delivery_window_start && new Date(delivery.delivery_window_start).getTime() <= now + 86400000); const pendingCosts = data.transactionCosts.filter((cost) => cost.costing_status === "pending"); return [{ label: `${low.length} low-stock material${low.length === 1 ? "" : "s"}`, detail: low.map((item) => item.name).slice(0, 3).join(", "), href: "/admin/materials?view=catalog", tone: "warning", count: low.length }, { label: `${negative.length} negative available balance${negative.length === 1 ? "" : "s"}`, detail: "Review reservations and authorized overrides.", href: "/admin/materials?view=movements", tone: "danger", count: negative.length }, { label: `${pendingCosts.length} material cost entr${pendingCosts.length === 1 ? "y" : "ies"} to review`, detail: "Crew job use stays pending until authorized cost review.", href: "/admin/materials?view=movements", tone: "warning", count: pendingCosts.length }, { label: `${missingReceipts.length} disposal receipt${missingReceipts.length === 1 ? "" : "s"} missing`, detail: "Completed paid loads need supporting paperwork.", href: "/admin/materials?view=disposal", tone: "warning", count: missingReceipts.length }, { label: `${staleStockpiles.length} stockpile estimate${staleStockpiles.length === 1 ? "" : "s"} stale`, detail: "Latest measurement is more than 30 days old.", href: "/admin/materials?view=production", tone: "info", count: staleStockpiles.length }, { label: `${dueDeliveries.length} ${dueDeliveries.length === 1 ? "delivery" : "deliveries"} due`, detail: "Planned within the next 24 hours or overdue.", href: "/admin/materials?view=deliveries", tone: "info", count: dueDeliveries.length }].filter((alert) => alert.count > 0); }
function materialName(data: MaterialWorkspaceData, id: string | null) { return data.materials.find((item) => item.id === id)?.name ?? "Unclassified material"; }
function locationName(data: MaterialWorkspaceData, id: string | null) { return id ? data.locations.find((item) => item.id === id)?.name ?? "Unknown location" : "Outside inventory"; }
function jobName(data: MaterialWorkspaceData, id: string | null) { const job = data.jobs.find((item) => item.id === id); const customer = Array.isArray(job?.customers) ? job.customers[0] : job?.customers; return job ? `${materialLabel(job.service_type || "work order")} for ${customer?.display_name ?? "customer"}` : "No work order"; }
function organizationName(data: MaterialWorkspaceData, id: string | null) { return data.organizations.find((item) => item.id === id)?.name ?? null; }
function customerName(data: MaterialWorkspaceData, id: string | null) { return data.customers.find((item) => item.id === id)?.display_name ?? "customer"; }
function money(cents: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(cents) / 100); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
function tabIcon(view: string) { const Icon = view === "catalog" ? Boxes : view === "movements" || view === "disposal" || view === "deliveries" ? Truck : view === "production" ? Factory : view === "purchases" ? ReceiptText : view === "reservations" ? PackageCheck : Scale; return <Icon size={17} />; }
