import Link from "next/link";
import { AlertTriangle, Award, Search, UserPlus, UsersRound } from "lucide-react";
import { EmployeeForm, QualificationRequirementsForm } from "./EmployeeForms";
import { PlatformFrame } from "@/components/PlatformFrame";
import { SetupRequired } from "@/components/SetupRequired";
import { getAuthenticatedPlatformContext } from "@/lib/auth/pageContext";
import { hasAllowedRole, platformRoleGroups } from "@/lib/auth/roles";
import { getEmployeeDashboardSummary, getEmployeeFormOptions, getEmployees, type EmployeeListRow } from "@/lib/data/employees";

type Props = { searchParams: Promise<{ q?: string; status?: string; crew?: string; role?: string; supervisor?: string; onboarding?: string; credential?: string; training?: string; access?: string; new?: string; archived?: string }> };
export default async function EmployeesPage({ searchParams }: Props) {
  const query = await searchParams; const context = await getAuthenticatedPlatformContext("/admin/employees");
  if (!context.configured) return <SetupRequired title="Configure Supabase before opening employees" />;
  const [employeesResult, options, summary] = await Promise.all([getEmployees(), getEmployeeFormOptions(), getEmployeeDashboardSummary()]);
  const canAdmin = hasAllowedRole(context.roles, platformRoleGroups.accessApproval); const employees = employeesResult.data.filter((employee) => matches(employee, query));
  return <PlatformFrame active="employees" roles={context.roles} userEmail={context.user.email}><div className="shell app-content employee-page">
    <section className="page-heading commerce-heading"><div><p className="surface-label"><UsersRound size={17} />Employee operations</p><h1>Employees</h1><p>Onboarding, qualifications, training, safety, access, and issued equipment without mixing employment history into authentication.</p></div>{canAdmin ? <Link className="primary-action" href="/admin/employees?new=1"><UserPlus size={18} />Add employee</Link> : null}</section>
    {query.archived ? <p className="form-message success">Employee archived. Historical records remain preserved.</p> : null}
    {[employeesResult.error, options.error, summary.error].filter(Boolean).map((message) => <DataWarning key={message} message={message ?? ""} />)}
    <section className="employee-summary-grid"><Summary label="Onboarding" value={summary.data.onboarding.length} tone="info" /><Summary label="Credentials expiring" value={summary.data.expiring.length} tone="warning" /><Summary label="Expired credentials" value={summary.data.expired.length} tone="danger" /><Summary label="Documents awaiting review" value={summary.data.pendingDocuments.length} tone="warning" /></section>
    <form className="employee-filter-bar" method="get"><label className="employee-search"><Search size={18} /><input defaultValue={query.q ?? ""} name="q" placeholder="Search employee, number, title, or crew" /></label><label>Status<select defaultValue={query.status ?? ""} name="status"><option value="">All statuses</option>{["applicant","onboarding","active","seasonal","leave","inactive","separated"].map((value) => <option key={value} value={value}>{title(value)}</option>)}</select></label><label>Crew<select defaultValue={query.crew ?? ""} name="crew"><option value="">All crews</option>{Array.from(new Set(employeesResult.data.map((employee) => employee.crew_name).filter(Boolean))).map((value) => <option key={value} value={value ?? ""}>{value}</option>)}</select></label><label>Supervisor<select defaultValue={query.supervisor ?? ""} name="supervisor"><option value="">All supervisors</option>{options.supervisors.map((employee) => <option key={employee.id} value={employee.id}>{employee.preferred_name || employee.legal_name || "Supervisor"}</option>)}</select></label><label>Role<select defaultValue={query.role ?? ""} name="role"><option value="">All roles</option>{["crew","estimator","payroll_admin","admin"].map((value) => <option key={value} value={value}>{title(value)}</option>)}</select></label><label>Onboarding<select defaultValue={query.onboarding ?? ""} name="onboarding"><option value="">Any progress</option><option value="incomplete">Incomplete</option><option value="complete">Complete</option></select></label><label>Credential<select defaultValue={query.credential ?? ""} name="credential"><option value="">Any credential state</option>{["current","expiring","expired","pending","none"].map((value) => <option key={value} value={value}>{title(value)}</option>)}</select></label><label>Training<select defaultValue={query.training ?? ""} name="training"><option value="">Any training</option><option value="recorded">Training recorded</option><option value="none">No training recorded</option></select></label><button className="secondary-action" type="submit">Apply filters</button></form>
    <div className="crm-layout"><section className="crm-main"><div className="record-list employee-record-list">{employees.length ? employees.map((employee) => <EmployeeCard employee={employee} key={employee.id} />) : <section className="empty-state"><h2>No employees match</h2><p>Clear the filters or create the first operational employee record.</p></section>}</div></section><aside className="crm-side">{query.new === "1" && canAdmin ? <section className="form-panel employee-create-panel"><h2>Add employee</h2><p>Create the operational record now. Platform access can be approved separately later.</p><EmployeeForm canSeePrivate={canAdmin} supervisors={options.supervisors} /></section> : <><section className="notice-panel"><strong>Employment record and login are separate</strong><p>An employee can exist before access approval. Disabling their account does not delete time, jobs, training, credentials, acknowledgments, or equipment history.</p></section><div className="quick-action-list"><Link href="/admin/training">Record training</Link><Link href="/admin/safety">Safety meetings</Link><Link href="/admin/access">Review access requests</Link></div></>}</aside></div>
    {canAdmin ? <section className="panel employee-qualification-panel"><div className="panel-header"><div><h2>Qualification warning rules</h2><p>Configure company assignment warnings. These are operational reminders, not legal determinations.</p></div></div><QualificationRequirementsForm credentialTypes={options.credentialTypes} requirements={options.qualificationRequirements} /></section> : null}
  </div></PlatformFrame>;
}
function EmployeeCard({ employee }: { employee: EmployeeListRow }) { return <article className="record-card employee-card"><div className="record-card-header"><div><p className="record-kicker">{employee.employee_number || "No employee number"}</p><h2>{employee.preferred_name || employee.legal_name || "Employee"}</h2></div><span className={`employee-status status-${employee.employment_status}`}>{title(employee.employment_status)}</span></div><p>{employee.job_title || "Job title not set"}{employee.crew_name ? ` · ${employee.crew_name}` : ""}</p><div className="employee-card-signals"><span><strong>{employee.onboardingProgress}%</strong> onboarding</span><span className={`credential-${employee.credentialState}`}><Award size={15} />{title(employee.credentialState)}</span><span>{title(employee.platformAccessState)} access</span></div>{["expired","expiring","pending"].includes(employee.credentialState) ? <p className="employee-attention"><AlertTriangle size={16} />Credential attention needed</p> : null}<Link className="secondary-action" href={`/admin/employees/${employee.id}`}>Open employee record</Link></article>; }
function Summary({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`employee-summary-card ${tone}`}><strong>{value}</strong><span>{label}</span></article>; }
function matches(employee: EmployeeListRow, query: Awaited<Props["searchParams"]>) { const q = query.q?.toLowerCase().trim(); return (!query.status || employee.employment_status === query.status) && (!query.crew || employee.crew_name === query.crew) && (!query.supervisor || employee.supervisor_employee_id === query.supervisor) && (!query.role || employee.roleNames.includes(query.role)) && (!query.onboarding || (query.onboarding === "complete" ? employee.onboardingProgress === 100 : employee.onboardingProgress < 100)) && (!query.credential || employee.credentialState === query.credential) && (!query.training || employee.trainingState === query.training) && (!query.access || employee.platformAccessState === query.access) && (!q || [employee.legal_name, employee.preferred_name, employee.employee_number, employee.job_title, employee.crew_name].some((value) => value?.toLowerCase().includes(q))); }
function title(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function DataWarning({ message }: { message: string }) { return <section className="data-warning"><strong>Database notice</strong><p>{message}</p></section>; }
