import Link from "next/link";
import { Building2, CalendarClock, FilePlus2, MapPin, Pencil, ReceiptText, ShieldCheck, UserRound } from "lucide-react";
import { ChangeOrderPortalPanel, ChangeOrderWorkflowPanel, DuplicateChangeOrderButton } from "@/components/change-order-forms";
import { PlatformFrame } from "@/components/PlatformFrame";
import { SetupRequired } from "@/components/SetupRequired";
import { getAuthenticatedPlatformContext } from "@/lib/auth/pageContext";
import { getChangeOrderActivity, getChangeOrderDetail, getChangeOrderTokens } from "@/lib/data/change-orders";

type Props = { params: Promise<{ changeOrderId: string }>; searchParams: Promise<{ updated?: string }> };

export default async function ChangeOrderDetailPage({ params, searchParams }: Props) {
  const { changeOrderId } = await params;
  const query = await searchParams;
  const context = await getAuthenticatedPlatformContext(`/admin/change-orders/${changeOrderId}`);
  if (!context.configured) return <SetupRequired title="Configure Supabase before opening change orders" />;
  const [detail, tokens, activity] = await Promise.all([getChangeOrderDetail(changeOrderId), getChangeOrderTokens(changeOrderId), getChangeOrderActivity(changeOrderId)]);
  const order = detail.data;
  const manuallyApproved = Boolean(order?.approved_at && order.approval_method && order.approval_method !== "portal");
  return (
    <PlatformFrame active="change-orders" roles={context.roles} userEmail={context.user.email}>
      <div className="shell app-content commerce-page">
        <Link className="crew-back-link" href={order?.job_id ? `/admin/jobs/${order.job_id}#job-scope` : "/admin/change-orders"}>{order?.job_id ? "Back to work order" : "Back to work additions"}</Link>
        {detail.error ? <Warning message={detail.error} /> : null}{tokens.error ? <Warning message={`Customer links: ${tokens.error}`} /> : null}{activity.error ? <Warning message={`Activity history: ${activity.error}`} /> : null}{query.updated === "1" ? <p className="form-message success">Changes saved. Existing customer link remains active.</p> : null}
        {!order ? <section className="empty-state"><h1>Change order unavailable</h1></section> : <>
          <section className="commerce-detail-header"><div><p className="surface-label"><FilePlus2 size={18} /> Additional-work agreement</p><h1>{order.change_order_number}</h1><p>{order.title}</p></div><div className="commerce-header-aside"><span className={`status-pill change-order-status ${order.status}`}>{order.status.replaceAll("_", " ")}</span>{manuallyApproved ? <span className="status-pill approval-source manual"><ShieldCheck size={15} /> Manually approved</span> : order.approval_method === "portal" ? <span className="status-pill approval-source portal"><ShieldCheck size={15} /> Portal approved</span> : null}<strong>{money(order.total_cents)}</strong>{["draft", "pending_internal_review", "ready_to_send", "sent", "change_requested"].includes(order.status) ? <Link className="primary-action" href={`/admin/change-orders/${order.id}/edit`}><Pencil size={17} /> Edit</Link> : null}<DuplicateChangeOrderButton id={order.id} /></div></section>
          <section className="commerce-detail-layout"><main className="commerce-document-column">
            <section className="commerce-document-panel change-order-document"><header><div><p className="surface-label">Angel Tree Services</p><h2>Change Order</h2></div><div><strong>{order.change_order_number}</strong><span>Created {date(order.created_at)}</span></div></header><div className="change-order-document-party"><div><span>{order.organizations ? "Organization" : "Customer"}</span><strong>{order.organizations?.name ?? order.customers?.display_name ?? "Unknown account"}</strong>{order.approval_contact ? <p>Attention: {order.approval_contact.full_name}</p> : null}</div><div><span>Service location</span><strong>{location(order)}</strong></div></div><section><h3>Reason and added scope</h3>{order.reason ? <p>{order.reason}</p> : null}{order.customer_description ? <p className="business-document-preformatted">{order.customer_description}</p> : null}</section><div className="line-items-preview commerce-line-items">{(order.change_order_line_items ?? []).sort((a, b) => a.sort_order - b.sort_order).map((line) => <div className="line-item-row" key={line.id}><span className="formatted-line-description"><strong>{line.title}</strong>{line.description ? <span>{line.description}</span> : null}</span><span>{line.quantity} {line.unit ?? ""}</span><span>{money(line.unit_price_cents)}</span><strong>{money(line.amount_cents)}</strong></div>)}</div><dl className="change-order-total-comparison"><div><dt>Original approved amount</dt><dd>{money(order.original_approved_amount_cents)}</dd></div><div><dt>Additional proposed amount</dt><dd>{money(order.total_cents)}</dd></div><div><dt>Revised combined total</dt><dd>{money(order.original_approved_amount_cents + order.total_cents)}</dd></div></dl>{order.customer_notes ? <section><h3>Additional notes</h3><p className="business-document-preformatted">{order.customer_notes}</p></section> : null}</section>
            <section className="commerce-side-panel"><h2 className="panel-title"><ShieldCheck size={18} /> Approval record</h2>{order.approved_at ? <>{order.approval_method ? <p className="field-note">{manuallyApproved ? "Manually approved outside the customer portal." : "Approved through the secure customer portal."}</p> : null}<dl className="record-details"><div><dt>Approved by</dt><dd>{order.approved_by_name ?? "Recorded approval"}</dd></div><div><dt>Method</dt><dd>{order.approval_method?.replaceAll("_", " ") ?? "Not recorded"}</dd></div><div><dt>Approved</dt><dd>{dateTime(order.approved_at)}</dd></div><div><dt>Applied to job</dt><dd>{dateTime(order.applied_to_job_at)}</dd></div>{order.approval_notes ? <div><dt>Approval notes</dt><dd className="business-document-preformatted">{order.approval_notes}</dd></div> : null}</dl></> : <p className="inline-empty">Customer approval has not been recorded.</p>}</section>
            {order.internal_notes ? <section className="commerce-side-panel internal-only-panel"><h2>Internal supporting information</h2><p className="business-document-preformatted">{order.internal_notes}</p><small>Never shown in the customer portal or email.</small></section> : null}
          </main><aside className="commerce-detail-sidebar">
            <section className="commerce-side-panel"><h2 className="panel-title"><ShieldCheck size={18} /> Workflow</h2><ChangeOrderWorkflowPanel order={order} /></section>
            <section className="commerce-side-panel"><ChangeOrderPortalPanel changeOrderId={order.id} tokens={tokens.data} /></section>
            <section className="commerce-side-panel"><h2 className="panel-title"><Building2 size={18} /> Account</h2>{order.organizations ? <Link className="linked-record" href={`/admin/organizations/${order.organizations.id}`}><strong>{order.organizations.name}</strong><span>Organization</span></Link> : order.customers ? <Link className="linked-record" href={`/admin/customers/${order.customers.id}`}><strong>{order.customers.display_name}</strong><span>Individual customer</span></Link> : null}{order.approval_contact ? <div className="linked-record"><strong>{order.approval_contact.full_name}</strong><span>Approval contact - {order.approval_contact.email || order.approval_contact.phone || "No contact details"}</span></div> : null}</section>
            <section className="commerce-side-panel"><h2 className="panel-title"><MapPin size={18} /> Property</h2><p>{location(order)}</p></section>
            <section className="commerce-side-panel"><h2 className="panel-title"><FilePlus2 size={18} /> Related records</h2>{order.source_quote ? <Link className="linked-record" href={`/admin/quotes/${order.source_quote.id}`}><strong>{order.source_quote.quote_number || "Approved quote"}</strong><span>Original amount {money(order.source_quote.total_cents)}</span></Link> : null}{order.jobs ? <Link className="linked-record" href={`/admin/jobs/${order.jobs.id}`}><strong>Work order</strong><span>{order.jobs.service_type?.replaceAll("_", " ") || order.jobs.status.replaceAll("_", " ")}</span></Link> : null}{order.invoices ? <Link className="linked-record" href={`/admin/invoices/${order.invoices.id}`}><strong>{order.invoices.invoice_number || "Invoice"}</strong><span>{order.invoices.status.replaceAll("_", " ")}</span></Link> : <p className="inline-empty">Not invoiced.</p>}</section>
            <section className="commerce-side-panel"><h2 className="panel-title"><CalendarClock size={18} /> Schedule impact</h2>{Object.entries(order.schedule_impact ?? {}).filter(([, value]) => value).length ? Object.entries(order.schedule_impact).filter(([, value]) => value).map(([key]) => <span className="status-pill attention" key={key}>{key.replaceAll("_", " ")}</span>) : <p className="inline-empty">No schedule impact recorded.</p>}<p className="field-note">Approval never moves the job automatically.</p></section>
            <section className="commerce-side-panel"><h2 className="panel-title"><ReceiptText size={18} /> Activity history</h2>{activity.data.length ? <div className="linked-record-list">{activity.data.map((event) => <article className="linked-record" key={event.id}><strong>{event.event_type.replaceAll("_", " ")}</strong><span>{dateTime(event.created_at)}</span></article>)}</div> : <p className="inline-empty">No activity recorded yet.</p>}</section>
          </aside></section>
        </>}
      </div>
    </PlatformFrame>
  );
}
function Warning({ message }: { message: string }) { return <section className="data-warning"><strong>Database notice</strong><p>{message}</p></section>; }
function money(cents: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100); }
function date(value: string) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(value)); }
function dateTime(value: string | null) { return value ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not yet"; }
function location(order: NonNullable<Awaited<ReturnType<typeof getChangeOrderDetail>>["data"]>) { const value = order.service_locations; return value ? [value.label, value.street, value.city, value.state, value.postal_code].filter(Boolean).join(", ") : "No service location attached"; }
