"use server";

import { revalidatePath } from "next/cache";
import { recordActivity } from "@/lib/activity-log";
import { createClient } from "@/lib/supabase/server";
import { prepareSafeUpload } from "@/lib/security/upload-validation";
import { safeStaffMessage } from "@/lib/security/errors";

export type EmployeeSelfActionState = { status: "idle" | "success" | "error"; message: string };

export async function submitEmployeeRequest(_state: EmployeeSelfActionState, formData: FormData): Promise<EmployeeSelfActionState> { const context = await getContext(); if (!context) return fail("Sign in before submitting a request."); const requestType = text(formData, "request_type", 40); const title = text(formData, "title", 180); const details = text(formData, "details", 3000); const { error } = await context.supabase.rpc("submit_my_employee_request", { p_request_type: requestType, p_title: title, p_details: details }); if (error) return fail(error.message); revalidatePath("/employee"); return ok("Request submitted for staff review."); }
export async function acknowledgeEmployeeItem(_state: EmployeeSelfActionState, formData: FormData): Promise<EmployeeSelfActionState> { const context = await getContext(); if (!context) return fail("Sign in before acknowledging an item."); const subjectType = text(formData, "subject_type", 40); const subjectId = text(formData, "subject_id", 80); const subjectVersion = text(formData, "subject_version", 80) || "1"; const name = text(formData, "acknowledgment_name", 180); if (!subjectId) return fail("Acknowledgment item is missing."); const { error } = await context.supabase.rpc("acknowledge_my_employee_item", { p_subject_type: subjectType, p_subject_id: subjectId, p_subject_version: subjectVersion, p_name: name }); if (error) return fail(error.message); const { data: self } = await context.supabase.rpc("get_my_employee_self_service"); const employeeId = self?.employee?.id as string | undefined; if (employeeId) await recordActivity(context.supabase, { actorUserId: context.user.id, eventType: "employee_acknowledgment_recorded", subjectId: employeeId, subjectType: "employee", metadata: { subject_type: subjectType, subject_id: subjectId, subject_version: subjectVersion } }); revalidatePath("/employee"); return ok("Acknowledgment recorded. This confirms receipt and does not waive legal rights."); }
export async function uploadMyCredentialDocument(_state: EmployeeSelfActionState, formData: FormData): Promise<EmployeeSelfActionState> { const context = await getContext(); if (!context) return fail("Sign in before uploading a document."); const { data: self, error: selfError } = await context.supabase.rpc("get_my_employee_self_service"); const employeeId = self?.employee?.id as string | undefined; if (selfError || !employeeId) return fail(selfError?.message ?? "No employee record is linked to this account."); const file = formData.get("file"); const title = text(formData, "title", 180); if (!(file instanceof File) || !title) return fail("Document title and file are required."); if (!["application/pdf","image/jpeg","image/png","image/webp"].includes(file.type) || file.size > 15*1024*1024) return fail("Upload a PDF, JPEG, PNG, or WebP file up to 15 MB."); const prepared = await prepareSafeUpload(file, { maxBytes: 15 * 1024 * 1024, allowDocuments: true }); if (!prepared.data) return fail(prepared.error ?? "The file could not be validated."); const path = `${employeeId}/submitted/${Date.now()}-${safeFileName(file.name)}`; const { error: uploadError } = await context.supabase.storage.from("employee-files").upload(path, prepared.data.bytes, { contentType: prepared.data.contentType, upsert: false }); if (uploadError) return fail(uploadError.message); const { error } = await context.supabase.rpc("submit_my_employee_document", { p_document_type: text(formData, "document_type", 80) || "credential", p_title: title, p_storage_path: path, p_mime_type: prepared.data.contentType, p_file_size_bytes: prepared.data.size, p_issue_date: date(formData, "issue_date"), p_expiration_date: date(formData, "expiration_date") }); if (error) { await context.supabase.storage.from("employee-files").remove([path]); return fail(error.message); } await recordActivity(context.supabase, { actorUserId: context.user.id, eventType: "employee_document_submitted", subjectId: employeeId, subjectType: "employee" }); revalidatePath("/employee"); revalidatePath("/admin/employees"); return ok("Document submitted. Staff must review it before any credential is verified."); }
async function getContext() { const supabase = await createClient(); if (!supabase) return null; const { data: { user } } = await supabase.auth.getUser(); return user ? { supabase, user } : null; }
function text(formData: FormData, key: string, max: number) { return String(formData.get(key) ?? "").trim().slice(0, max); } function date(formData: FormData, key: string) { const value = text(formData, key, 40); return /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : null; } function safeFileName(value: string) { return value.toLowerCase().replace(/[^a-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,100)||"file"; } function fail(message: string): EmployeeSelfActionState { return { status: "error", message: safeStaffMessage(message) }; } function ok(message: string): EmployeeSelfActionState { return { status: "success", message }; }
