"use client";

import { useReliableActionState } from "@/hooks/use-reliable-action-state";
import { CheckCircle2, FileUp, MessageSquarePlus } from "lucide-react";
import { acknowledgeEmployeeItem, submitEmployeeRequest, uploadMyCredentialDocument, type EmployeeSelfActionState } from "./actions";
const initialState: EmployeeSelfActionState = { status: "idle", message: "" };
export function EmployeeRequestForm() { const [state, action, pending] = useReliableActionState(submitEmployeeRequest, initialState); return <form action={action} className="crm-form employee-self-form"><Message state={state} /><label>Request type<select name="request_type"><option value="profile_correction">Profile correction</option><option value="credential_renewal">Credential renewed</option><option value="training_request">Training request</option><option value="document_review">Document review</option><option value="other">Other</option></select></label><label>Short title<input name="title" required /></label><label>Details<textarea name="details" required rows={4} /></label><button disabled={pending} type="submit"><MessageSquarePlus size={18} />{pending ? "Submitting..." : "Submit request"}</button></form>; }
export function EmployeeDocumentUploadForm() { const [state, action, pending] = useReliableActionState(uploadMyCredentialDocument, initialState); return <form action={action} className="crm-form employee-self-form"><Message state={state} /><div className="form-grid-two"><label>Document title<input name="title" required /></label><label>Document type<input name="document_type" placeholder="License, certification card..." /></label></div><div className="form-grid-two"><label>Issue date<input name="issue_date" type="date" /></label><label>Expiration date<input name="expiration_date" type="date" /></label></div><label>File<input accept="application/pdf,image/jpeg,image/png,image/webp" name="file" required type="file" /></label><button disabled={pending} type="submit"><FileUp size={18} />{pending ? "Uploading..." : "Submit for review"}</button></form>; }
export function EmployeeAcknowledgmentForm({ subjectId, subjectType, version = "1" }: { subjectId: string; subjectType: "training_session" | "safety_meeting" | "employee_document"; version?: string }) { const [state, action, pending] = useReliableActionState(acknowledgeEmployeeItem, initialState); return <form action={action} className="employee-ack-form"><input name="subject_id" type="hidden" value={subjectId} /><input name="subject_type" type="hidden" value={subjectType} /><input name="subject_version" type="hidden" value={version} /><label>Type your name<input name="acknowledgment_name" required /></label><button disabled={pending} type="submit"><CheckCircle2 size={17} />{pending ? "Recording..." : "Acknowledge"}</button><Message state={state} /></form>; }
function Message({ state }: { state: EmployeeSelfActionState }) { return state.message ? <p className={`form-message ${state.status}`} role={state.status === "error" ? "alert" : "status"}>{state.message}</p> : null; }
