import { Award, ClipboardCheck, FileText, ShieldCheck, Truck, UserRound } from "lucide-react";
import { EmployeeAcknowledgmentForm, EmployeeDocumentUploadForm, EmployeeRequestForm } from "./EmployeeSelfForms";
import { PlatformFrame } from "@/components/PlatformFrame";
import { SetupRequired } from "@/components/SetupRequired";
import { getAuthenticatedPlatformContext } from "@/lib/auth/pageContext";
import { getMyEmployeeSelfService } from "@/lib/data/employees";

export default async function EmployeeSelfPage() { const context = await getAuthenticatedPlatformContext("/employee"); if (!context.configured) return <SetupRequired title="Configure Supabase before opening employee profile" />; const result = await getMyEmployeeSelfService(); const data = result.data; return <PlatformFrame active="employee-self" roles={context.roles} userEmail={context.user.email}><div className="crew-shell app-content employee-self-page"><section className="crew-hero"><p className="surface-label"><UserRound size={18} />My employee profile</p><h1>{data?.employee.preferred_name || data?.employee.legal_name || "Employee profile"}</h1><p>Review your onboarding, qualifications, training, safety acknowledgments, documents, and issued equipment. Staff review all corrections and credentials.</p></section>{result.error ? <section className="data-warning"><strong>Employee profile unavailable</strong><p>{result.error}</p></section> : null}{!data ? <section className="crew-panel"><h2>No linked employee record</h2><p>Ask an administrator to link your employee record to this platform account.</p></section> : <>
    <section className="employee-self-summary"><article><small>Status</small><strong>{title(data.employee.employment_status)}</strong></article><article><small>Job title</small><strong>{data.employee.job_title || "Not set"}</strong></article><article><small>Crew</small><strong>{data.employee.crew_name || "Not assigned"}</strong></article><article><small>Onboarding</small><strong>{progress(data.onboarding)}%</strong></article></section>
    <section className="crew-panel"><div className="crew-panel-heading"><span className="crew-panel-icon"><ClipboardCheck size={20} /></span><div><h2>Onboarding progress</h2><p>Only authorized staff can verify required tasks.</p></div></div><div className="employee-self-list">{data.onboarding.map((item) => <article key={item.id}><strong>{item.label}</strong><span className={`self-status ${item.status}`}>{title(item.status)}</span></article>)}</div></section>
    <section className="crew-panel"><div className="crew-panel-heading"><span className="crew-panel-icon"><Award size={20} /></span><div><h2>Credentials and training</h2><p>Expiration labels are reminders, not legal determinations.</p></div></div><div className="employee-self-list">{data.credentials.map((credential) => <article key={credential.id}><strong>{credential.type}</strong><span className={credential.expiration_date && new Date(credential.expiration_date) < new Date() ? "attention-text" : ""}>{credential.expiration_date ? `Expires ${formatDate(credential.expiration_date)}` : title(credential.status)}</span></article>)}{data.training.map((training) => <article key={training.id}><strong>{training.title}</strong><span>{title(training.result)} · {formatDate(training.starts_at)}</span>{training.acknowledged_at ? <small>Acknowledged {formatDate(training.acknowledged_at)}</small> : <EmployeeAcknowledgmentForm subjectId={training.id} subjectType="training_session" version={training.document_version || training.id} />}</article>)}</div></section>
    <section className="crew-panel"><div className="crew-panel-heading"><span className="crew-panel-icon"><ShieldCheck size={20} /></span><div><h2>Safety meetings</h2><p>Acknowledgment confirms receipt; it is not a waiver of legal rights.</p></div></div><div className="employee-self-list">{data.safety_meetings.map((meeting) => <article key={meeting.id}><strong>{meeting.title}</strong><span>{formatDate(meeting.starts_at)} · {title(meeting.attendance_status)}</span>{!meeting.acknowledged_at && meeting.attendance_status === "present" ? <EmployeeAcknowledgmentForm subjectId={meeting.id} subjectType="safety_meeting" version={meeting.document_version || meeting.id} /> : <small>{meeting.acknowledged_at ? "Acknowledged" : "No acknowledgment required"}</small>}</article>)}</div></section>
    <section className="crew-panel"><div className="crew-panel-heading"><span className="crew-panel-icon"><Truck size={20} /></span><div><h2>Issued equipment and PPE</h2><p>Report missing, damaged, or incorrectly assigned items to staff.</p></div></div><div className="employee-self-list">{data.issued_equipment.length ? data.issued_equipment.map((item) => <article key={item.assignment_id}><strong>{item.asset_number} · {item.name}</strong><span>{item.returned_at ? `Returned ${formatDate(item.returned_at)}` : item.expected_return_at ? `Return expected ${formatDate(item.expected_return_at)}` : "Currently issued"}</span></article>) : <p>No issued equipment is recorded.</p>}</div></section>
    <section className="crew-panel"><div className="crew-panel-heading"><span className="crew-panel-icon"><FileText size={20} /></span><div><h2>Employee-visible documents</h2><p>Private files use short-lived links.</p></div></div><div className="employee-self-list">{data.documents.map((document) => <article key={document.id}><strong>{document.title}</strong><span>{title(document.review_status)}{document.expiration_date ? ` · expires ${formatDate(document.expiration_date)}` : ""}</span>{document.signed_url ? <a className="secondary-action" href={document.signed_url} rel="noreferrer" target="_blank">Open file</a> : null}<EmployeeAcknowledgmentForm subjectId={document.id} subjectType="employee_document" version={document.id} /></article>)}</div><details className="employee-self-details"><summary>Submit renewed credential or document</summary><EmployeeDocumentUploadForm /></details></section>
    <section className="crew-panel"><h2>Request a correction or training</h2><EmployeeRequestForm /><div className="employee-self-list">{data.requests.map((request) => <article key={request.id}><strong>{request.title}</strong><span>{title(request.status)} · {formatDate(request.created_at)}</span>{request.review_notes ? <small>{request.review_notes}</small> : null}</article>)}</div></section>
  </>}</div></PlatformFrame>; }
function title(value: string) { return value.replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase()); } function formatDate(value: string) { return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value)); } function progress(items: { status: string }[]) { return items.length ? Math.round(items.filter((item)=>item.status!=="incomplete").length/items.length*100) : 0; }
