import { CheckCircle2, FilePlus2, Leaf, MapPin, ShieldCheck } from "lucide-react";
import { PortalChangeOrderActions } from "@/components/portal-change-order-actions";
import { getChangeOrderByPortalToken } from "@/lib/data/change-orders";
import { checkPortalPageRateLimit } from "@/lib/security/portal-rate-limit";

export default async function ChangeOrderPortalPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const rateLimit = await checkPortalPageRateLimit("change-order", token);
  if (!rateLimit.available) return <Unavailable message="This secure change order is temporarily unavailable. Please try again shortly." />;
  if (!rateLimit.allowed) return <Unavailable message="Please wait a moment before opening this secure change order again." />;
  const lookup = await getChangeOrderByPortalToken(token);
  if (!lookup.changeOrder) return <Unavailable message={lookup.message} />;
  const order = lookup.changeOrder;
  const closed = ["approved", "declined", "cancelled", "expired"].includes(order.status);
  return <main className="customer-portal-page customer-change-order-page">
    <header className="customer-portal-header"><div className="customer-portal-brand"><span><Leaf size={22} /></span><div><strong>Angel Tree Services</strong><small>Fredericksburg, Virginia</small></div></div><p><ShieldCheck size={17} /> Secure additional-work review</p></header>
    <section className="customer-portal-hero customer-change-order-hero"><div className="customer-portal-intro"><p className="surface-label"><FilePlus2 size={18} /> Change order</p><h1>{closed ? "Your response is on file." : "Review this additional work."}</h1><p>The original approved quote remains unchanged. This page covers only the added or changed scope below.</p></div><aside className="customer-portal-summary-card"><span>Additional proposed amount</span><strong className="customer-change-order-total">{money(order.total_cents)}</strong><dl className="customer-quote-summary-list"><div><dt>Reference</dt><dd>{order.change_order_number}</dd></div><div><dt>Status</dt><dd>{order.status.replaceAll("_", " ")}</dd></div><div><dt>Property</dt><dd>{location(order)}</dd></div></dl></aside></section>
    <section className="customer-quote-workspace"><div className="customer-quote-document-column"><section className="commerce-document-panel change-order-document"><header><div><p className="surface-label">Angel Tree Services</p><h2>Additional Work Authorization</h2></div><strong>{order.change_order_number}</strong></header><div className="change-order-document-party"><div><span>{order.organizations ? "Organization" : "Customer"}</span><strong>{order.organizations?.name ?? order.customers?.display_name ?? "Customer"}</strong>{order.approval_contact ? <p>Attention: {order.approval_contact.full_name}</p> : null}</div><div><span>Service location</span><strong>{location(order)}</strong></div></div><section><h3>What is changing</h3><p className="business-document-preformatted">{order.customer_description || order.reason || "See the added line items below."}</p></section><div className="line-items-preview commerce-line-items">{(order.change_order_line_items ?? []).sort((a, b) => a.sort_order - b.sort_order).map((line) => <div className="line-item-row" key={line.id}><span className="formatted-line-description"><strong>{line.title}</strong>{line.description ? <span>{line.description}</span> : null}</span><span>{line.quantity} {line.unit ?? ""}</span><span>{money(line.unit_price_cents)}</span><strong>{money(line.amount_cents)}</strong></div>)}</div><dl className="change-order-total-comparison"><div><dt>Original approved amount</dt><dd>{money(order.original_approved_amount_cents)}</dd></div><div><dt>Additional proposed amount</dt><dd>{money(order.total_cents)}</dd></div><div><dt>Revised combined total</dt><dd>{money(order.original_approved_amount_cents + order.total_cents)}</dd></div></dl>{order.customer_notes ? <section><h3>Additional notes</h3><p className="business-document-preformatted">{order.customer_notes}</p></section> : null}</section></div><aside className="customer-quote-action-column">{order.status === "approved" ? <section className="customer-quote-confirmation"><CheckCircle2 size={24} /><div><h2>Additional work approved</h2><p>Angel Tree Services will confirm any schedule or coordination changes.</p></div></section> : closed ? <section className="customer-quote-confirmation"><ShieldCheck size={24} /><div><h2>Response recorded</h2><p>This change order is {order.status.replaceAll("_", " ")}.</p></div></section> : <PortalChangeOrderActions token={token} />}</aside></section>
    <footer className="customer-portal-footer"><strong>Angel Tree Services</strong><span>Questions? Reply to the email that included this secure link.</span></footer>
  </main>;
}
function Unavailable({ message }: { message: string }) { return <main className="customer-portal-page customer-portal-unavailable"><div className="customer-portal-brand"><span><Leaf size={22} /></span><div><strong>Angel Tree Services</strong><small>Secure customer portal</small></div></div><section><ShieldCheck size={28} /><h1>Change order link unavailable</h1><p>{message}</p></section></main>; }
function money(cents: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100); }
function location(order: NonNullable<Awaited<ReturnType<typeof getChangeOrderByPortalToken>>["changeOrder"]>) { const value = order.service_locations; return value ? [value.label, value.street, value.city, value.state, value.postal_code].filter(Boolean).join(", ") : "No service location attached"; }
